### ISSUE TITLE
"Country code" for WMO and Partner Organisations

### ISSUE THREAD

**Issue by tomkralidis** [wmo-im/wis2-topic-hierarchy#1]
(from @golfvert; manually moved from https://github.com/wmo-cop/wis2-topic-hierarchy/issues/1)

According to https://www.iso.org/glossary-for-iso-3166.html

```
User-assigned codes - If users need code elements to represent country names not included in ISO 3166-1, the series of letters AA, QM to QZ, XA to XZ, and ZZ, and the series AAA to AAZ, QMA to QZZ, XAA to XZZ, and ZZA to ZZZ respectively, and the series of numbers 900 to 999 are available.
NOTE: Please be advised that the above series of codes are not universal, those code elements are not compatible between different entities.
```

for Partner Organisation without a Country Code (eg. ECMWF, EUMETSAT, ESA,...) we can choose a 3-letter acronym in the list of user-assigned.

XPO seems to be used by Interpol (XPO is used for [Interpol travel documents](https://en.wikipedia.org/wiki/Interpol_passport)) so, what do we choose APO ? AAA ? ZZZ ? and then that would mean (eg) ZZZ.ECMWF in the topic tree.

**Comment by tomkralidis** [comment]
cc @efucile

We could also use numbers (`999`, so `999.ecmwf`).

**Comment by SimonElliottEUM** [comment]
Perhaps we could recall the part closest to this from the Manual on the GTS:  
_Country, organization and the production centre; the country shall be represented by the official ISO 3166 standard 2-letter code. 
Example: <gb-metoffice-exeter>. Each field shall be separated by the symbol “-” . The ISO 3166 standard 2-letter code xx shall be used for international organizations and shall therefore be the two first characters of the location indicator of international organizations, 
for example, “xx-eumetsat-darmstadt”, “xx-ecmwf-reading”._

In fact we us "XX-EUMETSAT-Darmstadt" for all files we send in the WIS

**Comment by kaiwirt** [comment]
Wikipedia says
XXX is used to represent a person of unspecified nationality

**Comment by golfvert** [comment]
We saw that... However, xXx has another meaning that our colleagues from supra-nationals organisations may not like :)

The wikipedia pages says:

User-assigned code elements
User-assigned code elements are codes at the disposal of users who need to add further names of countries, territories, or other geographical entities to their in-house application of ISO 3166-1, and the ISO 3166/MA will never use these codes in the updating process of the standard. The following alpha-3 codes can be user-assigned: AAA to AAZ, QMA to QZZ, XAA to XZZ, and ZZA to ZZZ.[5]

So, as for RFC1918 we can use and manage private designation. 
Option 1. : all centers (ECMWF, EUMETSAT,...) are under the same country code - we thought about XXA (avoiding the triple X...)
Option 2. : each center has its own three letters code AAA, AAB,... 

Or a mix between 1. and 2. Each RA in WMO has a code XXA, XXB,... and all centers within that region use the same.

I would avoid 2. has it creates an unnecessary (IMHO) management hassle. The mix mode one per RA has some merits...

**Comment by SimonElliottEUM** [comment]
Noting that I would be very careful about relying on Wikipedia as a source of truth, either of the two options proposed by Remy would work fine. I slightly prefer the second option, but one choice for all would also (continue to) work.

**Comment by tomkralidis** [comment]
Proposal:
1. create a "global" code
  - `xxa`
2. create a code foreach WMO RA
  - `xxb`: RA I
  - `xxc:` RA II
  - `xxd`: RA III
  - `xxe`: RA IV
  - `xxf:` RA V
  - `xxg`: RA VI

Examples:
- ECMWF and EUMETSAT would use `xxg` (RA VI)
- Global services would use `xxa`

**Comment by tomkralidis** [comment]
PR in #28
