### ISSUE TITLE
add SHIP, BUOY and AMDAR topics 

### ISSUE THREAD

**Issue by amilan17** [wmo-im/wis2-topic-hierarchy#112]

**Comment by amilan17** [comment]
I | U | A |   | Single level aircraft reports (automatic) | 4 | 0 | AMDAR
-- | -- | -- | -- | -- | -- | -- | --
I | U | O |   | Profiles of aircraft observations in ascending/descending | 2 | 20 | AMDAR

**Comment by amilan17** [comment]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/amilan/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/amilan/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#467886" vlink="#96607D">


I | O | B |   | Buoy observations | 1 | 25 | BUOY
-- | -- | -- | -- | -- | -- | -- | --




</body>

</html>

**Comment by amilan17** [comment]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/amilan/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/amilan/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#467886" vlink="#96607D">


I | S | C | 46-59 | Climatic observations from marine stations | 1 | 20 | CLIMAT SHIP
-- | -- | -- | -- | -- | -- | -- | --
I | S | S | 01-19 | Synoptic observations from marine stations | 1 | 0 | SHIP
I | U | J | 40-59 | Upper wind from marine stations (entire sounding) | 2 | 2 | PILOT SHIP (Parts A, B, C and D)
I | U | K | 40-59 | Radio soundings from marine stations (up to 100hPa) | 2 | 5 | TEMP SHIP (Parts A, B)
I | U | S | 40-59 | Radiosondes/pibal reports from marine stations (entire sounding) | 2 | 5 | TEMP SHIP (Parts A, B, C and D)
I | U | U | 46-59 | Monthly statistics of data from marine stations | 2 | 26 | SHIP
I | U | W | 40-59 | Upper wind from marine stations (up to 100 hPa) | 2 | 2 | PILOT SHIP (parts A, B)



</body>

</html>

**Comment by amilan17** [comment]
@tomkralidis

**Comment by josusky** [comment]
I am not a data expert so I am not sure what is the difference between IUA and IUO AMDAR, but I have learned that when it comes to upperair soundings, the differentiation between "entire sounding" and "up to 100 hPa" is largely unnecessary. Typically a balloon is lunched twice (few times) per day, the size of the resulting observation is in order of 10kB so sending it to two different topics would be useless - same as was assigning different TTAA heading part for it.

**Comment by david-i-berry** [comment]
One question, should we be perpetuating the keywords from the old alphanumeric codes such as SHIP, TEMP, SYNOP, BUOY?

Data from some of the moored buoys is more similar to the data from the ships in terms of parameters reported.

**Comment by tomkralidis** [comment]
Note: as part of ocean data publication activities (with Scripps), we are experimenting with `.../weather/experimental/surface-based-observations/buoy`.

**Comment by amilan17** [comment]
closing because these are addressed in issue #147
