### ISSUE TITLE
add centre-ids that are defined by the registry 

### ISSUE THREAD

**Issue by amilan17** [wmo-im/wis2-topic-hierarchy#113]
https://github.com/wmo-im/global-registry/blob/develop/wis2-nodes/wis2nodes.csv

**Comment by amilan17** [comment]
@tomkralidis

**Comment by yhonda21** [comment]
> https://github.com/wmo-im/global-registry/blob/develop/wis2-nodes/wis2nodes.csv

This link is broken, isn't it?

**Comment by tomkralidis** [comment]
Closing in lieu of #135
