### ISSUE TITLE
Monitor Topic

### ISSUE THREAD

**Issue by antje-s** [wmo-im/wis2-topic-hierarchy#124]
In WIS-Guide a monitor topic is mentioned, e.g. under 2.7.3.1 "...Global Broker will not discard the message but will send a message on the monitor topic hierarchy to inform the originating centre and its GISC." and under 2.7.4.1 "...Global Cache decides not to cache data it should behave as though the cache property is set to false and send a message on the monitor topic hierarchy to inform the originating centre and its GISC.". Should we add the monitor value to WTH even if it is a separate subtree, so that everyone is aware of it and for clarity?

**Comment by amilan17** [comment]
https://github.com/wmo-im/tt-wismd/wiki/Meeting-2024-06-03 notes: 
Tom presented the issue;

**Comment by tomkralidis** [comment]
TT-WISMD 2024-06-03:
- PR at #144 
- enumerate a list of issues that each Global Service should report on (perhaps this goes into WNAM)
- overriding level 5; is there a better way?
- ACTION: TT-WISMD to review and provide recommendation
- for reporting, should we use a different version (not `a`), to clearly indicate a different payload and topic/subtree/logic?

**Comment by tomkralidis** [comment]
Closing given https://github.com/wmo-im/wis2-monitoring-alerting (discussion now in new activity/repo).
