### ISSUE TITLE
Add topics for climate earth system discipline

### ISSUE THREAD

**Issue by david-i-berry** [wmo-im/wis2-topic-hierarchy#125]
Proposed initial topics for climate domain (and mapping of GTS headers, see #147).

### Climate

name | description | source
--|--|--
monthly | Monthly values from land stations, e.g. CLIMAT |
daily | Daily values from land stations, e.g. DAYCLI |
sub-daily | Reprocessed hourly and other sub-daily observations from land stations |

**Comment by david-i-berry** [comment]
From the existing AHL we could have (under surface based observations):

|T1|T2|A1|II|Data type|BUFR data category|BUFR data sub-category|Proposed topic|
|-- |--|--|--|---------|------------------|----------------------|-------|
|I|S|C|01-45|Climatic observations from land station|0|20|./CLIMAT|
|I|S|C|60|Climatic observations (monthly reports of daily climate data)|0|21|./DAYCLI|

**Comment by david-i-berry** [comment]
It would be good to move away from the historic TAC keywords, I'd like to propose updating to monthly and daily, e.g. 

cache/a/wis2/<centre-id>/data/core/climate/surface-based-observations/monthly
cache/a/wis2/<centre-id>/data/core/climate/surface-based-observations/daily

**Comment by amilan17** [comment]
Should we close this issue, because these are included in https://github.com/wmo-im/wis2-topic-hierarchy/issues/147

**Comment by david-i-berry** [comment]
No, I think it's useful to keep the issues separate to make consultation easier.
