### ISSUE TITLE
Add satellite topics

### ISSUE THREAD

**Issue by amilan17** [wmo-im/wis2-topic-hierarchy#126]
Add all non-commercial with a status of operational, standby or commissioning as defined in the [OSCAR Satellite DB](https://space.oscar.wmo.int/spacecapabilities) using the following topics.

* weather > space-based-observations > _satellite_ > _instrument_
* space-weather > space-based-observations > _satellite_ > _instrument_ 

[satellite-topics-final-draft.xlsx](https://github.com/wmo-im/wis2-topic-hierarchy/files/14980503/satellite-topics-final-draft.xlsx)

~* weather > space-based-observations > orbit-type > sensor-type > satellite-name > data-type~
~* space-weather > space-based-observations > orbit-type > sensor-type > satellite-name > data-type~

**Comment by antje-s** [comment]
at the moment EUMETSAT/us-cimss use topics like 
weather/space-based-observations/satellite4nowcasting/Meteosat-10/ImageL1-5
weather/space-based-observations/satellite4nwp/METOP-B/IASIL1
so perhaps add a level for satellite4nowcasting/satellite4nwp (or replace orbit)
and first satellite-name?

**Comment by tomkralidis** [comment]
TT-WISMD 2024-03-25:
- CGMS agrees on structure
- we can do first pass based on geostationary and sun synchronous orbit types
- we can manage as a single CSV that tooling can create the hierarchy as TTLs

ACTION: @amilan17 to create single CSV for review/integration

**Comment by amilan17** [comment]
@wmo-im/tt-wismd - flat tree CSVs are now available for space-based-observations under weather and space-weather. I decided to name the files "index-flat-tree.csv", but of course this is not fixed 
I talked with @efucile after the meeting and the following is recommended.
1. include **all** operational non-commercial satellites 
1. change processing-level to data-type which will allow for adding other things such as ancillary data
1. only include processing level 0 and 1, because level 2 and level 3 are more like products and it probably needs more thought

**Comment by tomkralidis** [comment]
TT-WISMD 2024-04-22
- PR in #127 
- timing
  - CGMS to review/approve by 31 May 2024
  - we then have 6 weeks for FT2024-02 submission (mid-July 2024)
- @amilan17 to trigger @wmo-im/tt-wismd to review #127 when CGMS approved
- we need to update TTL generation scripts to support the flat CSV structure (@tomkralidis @josusky @antje-s)

**Comment by josusky** [comment]
Hi, I have checked the index-flat.csv files and I have two questions:
1. If a column is called "*-description" (e.g. "satellite-description"), shall it be treated as description for "*" (e.g. "satellite")? Seems obvious, but the code needs exact rules, so I am double checking. In other words, this 4-column tables represent two levels of TH.
2. The "instruments" are **usually** unique for each satellite. Therefore, do we want to create a sub-register "satellite" that will have about 200 entries and then for each of those a sub-register with "instrument" that will have a few _concepts_ (even if some concepts/instruments are not totally unique) ?

**Comment by amilan17** [comment]
@josusky
`If a column is called "X-description" (e.g. "satellite-description"), shall it be treated as description for "X" (e.g. "satellite")? `  --> YES, but I welcome other more elegant solutions if available.

**Comment by josusky** [comment]
@amilan17 In my second question I am not asking about topic uniqueness, but about fact that e.g. _instrument_ "cis" appears in _satellite_ "cluster-1" as well as "cluster-2", "cluster-3", and "cluster-4". That is, one topic will be, ".../cluster-1/cis", other will be ".../cluster-2/cis" etc.. The description "Cluster Ion Spectrometry experiment (CIS)" will the appear in 4 *.ttl files, but I think this is acceptable, we have this sort of duplication at other places too, I just felt need to point it out.

**Comment by josusky** [comment]
This is what I meant, typical subtree for a satellite looks like this:
```
wis/topic-hierarchy/earth-system-discipline/space-weather/space-based-observations/ace
wis/topic-hierarchy/earth-system-discipline/space-weather/space-based-observations/ace/swepam.ttl
wis/topic-hierarchy/earth-system-discipline/space-weather/space-based-observations/ace/mag.ttl
wis/topic-hierarchy/earth-system-discipline/space-weather/space-based-observations/ace/cris.ttl
wis/topic-hierarchy/earth-system-discipline/space-weather/space-based-observations/ace/epam.ttl
wis/topic-hierarchy/earth-system-discipline/space-weather/space-based-observations/ace/sepica.ttl
wis/topic-hierarchy/earth-system-discipline/space-weather/space-based-observations/ace/swics.ttl
wis/topic-hierarchy/earth-system-discipline/space-weather/space-based-observations/ace/swims.ttl
wis/topic-hierarchy/earth-system-discipline/space-weather/space-based-observations/ace/sis.ttl
wis/topic-hierarchy/earth-system-discipline/space-weather/space-based-observations/ace/uleis.ttl
```
where "ace" is a satellite and "swepam", "mag" etc are instruments. The duplication, repetition of instruments manifests like this:
```
$ find wis -name cis.ttl
wis/topic-hierarchy/earth-system-discipline/space-weather/space-based-observations/cluster-1/cis.ttl
wis/topic-hierarchy/earth-system-discipline/space-weather/space-based-observations/cluster-2/cis.ttl
wis/topic-hierarchy/earth-system-discipline/space-weather/space-based-observations/cluster-4/cis.ttl
wis/topic-hierarchy/earth-system-discipline/space-weather/space-based-observations/cluster-3/cis.ttl
```
that is instrument/concept "cis" is defined 4 times in 4 different sub-registers/satallites. Not a big deal.

**Comment by amilan17** [comment]
Thanks for the explanation
