### ISSUE TITLE
Radar data topic hierarchy

### ISSUE THREAD

**Issue by chenxiaoxia2019** [wmo-im/wis2-topic-hierarchy#140]
Cyprus WIS2 Node is now sending radar data using the Topic Hierarchy:

origin/a/wis2/cy-dom/data/core/weather/surface-based-observations/radar

Which topic hierarchy is radar data using?

**Comment by amilan17** [comment]
@chenxiaoxia2019 will one of the radars in this proposal work for Cyprus?

https://github.com/wmo-im/wis2-topic-hierarchy/issues/147 
* weather/surface-based-observations/wind-profile-radar
* weather/surface-based-observations/temperature-profile-radar

**Comment by amilan17** [comment]
this issue is superseded by https://github.com/wmo-im/wis2-topic-hierarchy/issues/152
