### ISSUE TITLE
create GTS to WIS2 crosswalk

### ISSUE THREAD

**Issue by tomkralidis** [wmo-im/wis2-topic-hierarchy#147]
As discussed at [TT-WISMD 2024-04-22](https://github.com/wmo-im/tt-wismd/wiki/Meeting-2024-04-22#notes) creating a crosswalk from AHL to WTH topic/subtopic.  The output should be a configuration (CSV, etc.) that will be added to WTH publication workflow and release artifacts.

@efucile / @antje-s to provide an update / first pass for [TT-WISMD 2024-06-03](https://github.com/wmo-im/tt-wismd/wiki/Meeting-2024-06-03).

cc @wmo-im/tt-wismd

**Comment by amilan17** [comment]
https://github.com/wmo-im/tt-wismd/wiki/Meeting-2024-06-03: mapping was introduced by Dave and Enrico

**Comment by david-i-berry** [comment]
3 issues (and associated branches) created for each Earth system discipline, see #125, #151 and #152. Suggest closing and move work to those issues.

**Comment by tomkralidis** [comment]
Closing in lieu of #125, #151, #152
