### ISSUE TITLE
Add topics for ocean earth system domain

### ISSUE THREAD

**Issue by david-i-berry** [wmo-im/wis2-topic-hierarchy#151]
**Update 08/10/24**

Following comments received via email the proposal has been updated, a new branch can be found at: 

https://github.com/wmo-im/wis2-topic-hierarchy/tree/oceanv2

Proposed initial topics for the ocean earth system domain based on GOOS networks and existing GTS headers (see #147):

Name | Description | Source
--|--|--
moored-buoys-and-moorings|Data from moored buoys and moorings|
drifting-buoys|Data from drifting buoys|
sea-ice|Sea ice observations|
drifting-ocean-profilers|Data from ocean profilers, e.g. Argo|
ship-surface|Along track surface observations from ships|
ship-sub-surface|Profile data measured from ships, e.g. XBT, CTD, etc.|
wave-buoys|Data from wave buoys|
tsunami-buoys|Data from tsunami buoys, e.g. DART buoys|
autonomous-surface-vehicles|Data from autonomous surface vehicles|
autonomous-underwater-vehicles|Data from autonomous underwater vehicles|
animal-borne-sensors|Data from animal borne sensors|
fixed-marine-platforms|Data from fixed surface platforms|
fixed-coastal-platforms|Data from fixed coastal stations, e.g. sea level monitoring station, HF radars etc|

**Comment by david-i-berry** [comment]
Response received from GOOS Observations Coordination Group (10th September 2024)

# WIS2.0 topic hierarchy-Ocean based observations

## Observation Coordination Group (OCG) response

OCG executive members have discussed the suggested topic hierarchy (Annex 1) for the ocean-based platform data.
Comments from the OCG Exb members;


1. The suggested hierarchy (Annex1) is based on the platform view of the system. With a wide variety of platform types, adding EOV/ECV based hierarchy makes it more meaningful, although as long as this is available as a readily searchable option, it may not need hard coding into the hierarchy.
   * e.g. ocean/surface-based-observations/EOV or ECV/fixed-marine-platforms
1. We suggest keeping the observing systems in the hierarchy that is broad enough to include a variety of similar observing systems. In line with this, we suggest the following changes
   * change gliders to autonomous underwater vehicles. (i.e. gliders, Autosub from UK, other underwater vehicles)
ocean/surface-based-observations/autonomous underwater vehicles
   * Change ocean-profilers (Argo) to include other platforms providing ocean profilers 
ocean/surface-based-observations/drifting ocean profilers
   * moored buoys category includes sub-surface measurements
ocean/surface-based-observations/moored-buoys-and-moorings
   * Sea-level is an EOV. Replace it with fixed coastal station that can include sea level stations (GLOSS) and HF Radar
ocean/surface-based-observations/fixed-marine-platforms
1. We are not clear whether this hierarchy will be used to search on each of these terms or work as tree branches , see comment 1 above. If it is the former, we are comfortable with the proposed hierarchy with the edits mentioned above and with or without the inclusion of EOV/ECV, preferably before the observing system similar to the example provided in bullet i).

_Question_: We would like to clarify how the data users will use this topic hierarchy. Please see our assumption in iii) above. 

## Annex 1

### Oceanographic data
ocean/surface-based-observations/fixed-marine-platforms
ocean/surface-based-observations/moored-buoys
ocean/surface-based-observations/drifting-buoys
ocean/surface-based-observations/wave-buoys
ocean/surface-based-observations/autonomous-sea-surface-vehicles
ocean/surface-based-observations/gliders
ocean/surface-based-observations/sea-level
ocean/surface-based-observations/animal-borne-sensors
ocean/surface-based-observations/ship-based-observations
ocean/surface-based-observations/ocean-profilers

### Meteorological / weather data
weather/surface-based-observations/ship-based-observations
weather/surface-based-observations/ship-based-radiosondes
weather/surface-based-observations/moored-buoys
weather/surface-based-observations/drifting-buoys
weather/surface-based-observations/fixed-marine-platforms
weather/surface-based-observations/autonomous-sea-surface-vehicles

**Comment by amilan17** [comment]
@david-i-berry @amilan17 or @tomkralidis update a new branch with requested changes for team to review.

**Comment by tomkralidis** [comment]
@david-i-berry / @amilan17 any update here?  Can we have a branch update for review?

**Comment by david-i-berry** [comment]
@kevin-obrien

To answer the questions [above](https://github.com/wmo-im/wis2-topic-hierarchy/issues/151#issuecomment-2352272089), starting with (3):

3. The topic hierarchy is used to subscribe to (and publish) alerts when new data files are available. The tree structure is used to subscribe to different domains and sub-domains through the use of wild cards, with the notifications containing additional (limited) metadata to enable further filtering. The topics are not intended to be used to discover / search the catalogues. (@tomkralidis please correct me if I am wrong).

Now (1) and (2):

1. Data on the WIS2 is packed into reports / BUFR messages containing multiple EOVs. As such, a EOV based approach would not work. However, the WIS2 metadata, used to discover datasets and topics to subscribe, will contain this information - both through controlled vocabularies and free text keywords.
2. Proposed changes made, see proposal at the top of this issues (and associated branch):

   https://github.com/wmo-im/wis2-topic-hierarchy/tree/oceanv2

**Comment by tomkralidis** [comment]
TT-WISMD 2024-10-22:
- @kevin-obrien to provide final confirmation in the next 1-2 days

**Comment by tomkralidis** [comment]
Update: we have a go ahead from @kevin-obrien.
