### ISSUE TITLE
centre_id or center_id

### ISSUE THREAD

**Issue by tomkralidis** [wmo-im/wis2-topic-hierarchy#16]
cc @golfvert @amilan17 @efucile 

We define `center-id` in the README, but `centre-id` in the topic CSVs.

**Comment by amilan17** [comment]
According to the WMO spelling list it should be centre. 

https://public.wmo.int/en/resources/language-resources/wmo-spelling-list

**Comment by golfvert** [comment]
If there is an existing convention (I was not aware of this) and it doesn't not work (double negation on purpose) then center is fine by me.

**Comment by efucile** [comment]
in all our INFCOM documents we used Center. Not sure why in the spelling list is centre. We never used that

**Comment by tomkralidis** [comment]
Going with `center_id`.

**Comment by sebvi** [comment]
I believe it was (is!) `centre` and not `center` because this is how it is defined in the Manual on Codes, see Common code table [ C-1](https://github.com/wmo-im/CCT/blob/master/C01.csv)

**Comment by tomkralidis** [comment]
Implemented as `centre_id`. Closing.

**Comment by tomkralidis** [comment]
One more time: `centre-id` is canonical.
