### ISSUE TITLE
Question on topics in weather

### ISSUE THREAD

**Issue by golfvert** [wmo-im/wis2-topic-hierarchy#162]
In the current weather.csv, I can see:

```
5 | ship-sub-hourly | Ship based weather observations with a reporting frequency < 1 hour |  
6 | fixed-marine-platforms-hourly | Hourly weather observations from fixed marine platforms, e.g. rigs and offshore platforms |  
7 | fixed-marine-platforms-sub-hourly | Weather observations from fixed marine platforms, e.g. rigs and offshore platforms, with a reporting frequency < 1 hour |  
8 | fixed-land-stations-sub-hourly | Weather observations from fixed land stations with a reporting frequency < 1 hour |  
9 | mobile-land-stations-sub-hourly | Weather observations from mobile land stations with a reporting frequency < 1 hour
```

What is the purpose of splitting hourly and sub-hourly ?

There is no fixed-land-stations-hourly for example. They are synop ?

**Comment by amilan17** [comment]
@david-i-berry

**Comment by david-i-berry** [comment]
In the marine domain we can have observations much more frequently than hourly, with the observations having different uses / application areas. We have the same for the land based observations. 

For example, the goal observing cycle for surface wind speed varies from an observation every 5 minutes to once an hour across the different application areas - excluding aeronautical meteorology. If we include aeronautical meteorology the goal is one observation every 5 seconds:

https://space.oscar.wmo.int/variables/view/wind_speed_near_surface

Additionally, based on the manual on WIGOS observations, synoptic observations are those made at the synoptic standard times (0000, 0100, 0200 etc). The definition used is:

> **Synoptic observation**. A specified basic set of meteorological information collected at a standard time of observation.

Those observations made sub-hourly tend to contain more than the basic set of variables.

**Comment by golfvert** [comment]
The **sole** purpose of creating different topics is to allow users to get some messages (eg. the subhourly) and not others (eg. hourly) or the opposite. Nothing more.
Is that a use case ? Is that useful to do those kinds of filtering ?

**Comment by david-i-berry** [comment]
Yes, that is the use case. 

Currently on the GTS we have different headers for:

- observations at the main synoptic hours from fixed land stations (0, 6, 12 18) (synop)
- observations at the intermediate synoptic hours from fixed land stations (3, 9, 15, 21) (synop)
- observations at non-standard time from fixed land stations (1, 2, 4, 5, etc) (synop)
- routine scheduled observations from automatic (fixed or mobile) land stations  (fixed-land-stations-sub-hourly)
- n minute observations from automatic (fixed or mobile) land stations (fixed-land-stations-sub-hourly)

These have been merged into the two topics. 

> There is no fixed-land-stations-hourly for example. They are synop ?

Yes, `fixed-land-stations-hourly` currently go to `synop`. It would make sense to rename to `fixed-land-stations-hourly` to be consistent with the others.  As background, synop was already in use / approved when the mapping from the GTS headers to WIS2 TH was done. The mapping can be found in issue https://github.com/wmo-im/wis2-topic-hierarchy/issues/147.

**Comment by golfvert** [comment]
I don't understand. 
I don't think we want to match what is done on the GTS in the Topic Hierarchy.
Again, as a user, what would be the benefit to filter using the Topic Hierarchy ?
Eg. we have the `datetime` in WNM. Therefore, if someone wants only hourly (for whatever reason) it is already possible with this.

**Comment by tomkralidis** [comment]
Can we use WCMP2 and/or WNM elements to determine the temporal granularity (WCMP2 `time.resolution` and/or WNM `properties.datetime` for the actual datetime)?

**Comment by david-i-berry** [comment]
Synoptic observations are defined here: https://library.wmo.int/idviewer/55063/20

If the intent is to use the `synop `topic for more than synoptic observations should it be renamed? e.g. `surface-land-observation` as per the WMO-No. 49 definition: https://library.wmo.int/idviewer/35722/19. 

And then the same for the marine observations?

**Comment by amilan17** [comment]
@tomkralidis @golfvert @efucile @antje-s 

The original proposal (https://github.com/wmo-im/wis2-topic-hierarchy/issues/152) was an attempt to ensure that there were topics available for data currently exchanged on the GTS. However, it looks like the datatypes represented by the proposed topics can fit under synop and temp topics per the current WTH definitions. 

Name | Description | Source
-- | -- | --
2 | synop | Surface observations |  
3 | temp | Upper air observations


@david-i-berry and I recommend to **remove all of topics from this proposal #152** in order to ensure that we have proper discussion time for the all surface-based-observations and potentially align with definitions in WMO manuals.

**Comment by david-i-berry** [comment]
To follow up on Anna's comment, the terms "Surface observations" and "Upper-air observations" are defined in WMO-No. 49 and we need to be aware of consistency across Manuals and the Technical Regulations.

![image](https://github.com/user-attachments/assets/072fa158-d78a-41d9-8ef6-8aae4261119a)

and 

![image](https://github.com/user-attachments/assets/bd350c8d-8aaa-422f-b881-aa1089a30758)

At the moment the definition used for `synop` and `temp `cover nearly all atmospheric observations.

**Comment by efucile** [comment]
@golfvert @tomkralidis I propose to drop the hourly from ship-hourly, fixed-marine-platforms-hourly and accept the change as proposed during fast track 2024-2. We need further discussion on the sub-hourly and I would keep all the sub-hourly items for the next fast track after discussion by relevant experts.

**Comment by golfvert** [comment]
I'd like to know who made that proposal ? 
For all domains, we are asking domain experts to work on this.
I'd like to ensure that we have "weather" experts in the loop.

**Comment by david-i-berry** [comment]
The request to do a cross-walk of GTS headers to WIS2 topics was made here:

https://github.com/wmo-im/tt-wismd/wiki/Meeting-2024-04-22#notes

An issue was subsequently created here:

https://github.com/wmo-im/wis2-topic-hierarchy/issues/147

Antje, Enrico and myself met to discuss the GTS to WIS2 topic mapping.  Originally, it was proposed to map GTS abbreviated headers ISA/01-29 (routine obs. from AWS) and ISA/30-59 (n-minute obs from AWS) to `weather/surface-based-observations/synop/sub-hourly`. Over subsequent discussions this was changed to `weather/surface-based-observations/fixed-land-stations-sub-hourly` (noting the definition of synoptic observations from the Manuals as those observations made at the standard hours). 

We also had topics like  `weather/surface-based-observations/synop/marine` and `weather/surface-based-observations/synop/marine/sub-hourly`. These became  `weather/surface-based-observations/ship-hourly` and `weather/surface-based-observations/ship-sub-hourly`.

The final outcome from the work resulted in the table in the issue. 

This was then discussed at the June meeting:

https://github.com/wmo-im/tt-wismd/wiki/Meeting-2024-06-03

Branches with the mappings were then created based on the mapping and presented to TT-WISMD here:

https://github.com/wmo-im/tt-wismd/wiki/Meeting-2024-06-28

PRs were subsequently made for the respective branches. GCOS were consulted for the climate related topics and GOOS OCG for the ocean topics. Changes were subsequently made to the ocean topics.

**Comment by golfvert** [comment]
Thank you for the history :)
Trying to map GTS headers with Topic Hierarchy seems a bit strange to me.
GTS Headers are for routing. Getting too much GTS messages might be a problem if the GTS link is slow and the MSS weak.
WTH is for filtering. Getting too much WNM is not a problem. Brokers are fast. Links are fast.
I think we should start from a clean plate. What is useful for users ? Then we can give names. And up to a point, names are also meaningless. There are just strings. In MQTT5 it is possible to map strings to number to avoid having too long strings to manage, for example.

For me, the only question when defining topics is the usefulness of having topic a and b or only a.
Then, calling topic a "synop" or "banana" is (almost) irrelevant or at least of second order after the usefulness.
Same for creating sublevels. Useful filtering yes/no. 

What is important is that all published "data_xyz" making a "logic" grouping are using the same topic string. 

A few months ago I wrote this cookbook: https://github.com/wmo-im/wis2-cookbook/blob/main/cookbook/sections/20240415_Earth%20domain%20topic%20hierarchy%20guidelines.adoc

I am happy to discuss the cookbook and then apply its principles.

**Comment by efucile** [comment]
to make sure that we can go forward with the fast track I would suggest to exclude the controversial entries from this fast track. These are the topics ending sub-hourly which will be discussed by @wmo-im/tt-wismd following the indications of @golfvert .
I suggest to delete hourly from the proposed topics ship-hourly, fixed-marine-platforms-hourly given that they are urgently required for data exchange and that they follow the indications provided by Remy. I would like to highlight that the aim of the task was not to find a one to one mapping of the GTS headers to WIS2 topic hierarchy, but to find a many to one mapping as we want to reduce significantly the number of items used in the topic. Nevertheless in some cases it is useful to have some extra topic and mostly in the case when data are part of  different operational programme or are not part of any operational programme yet. @golfvert I hope you will be able to accept this proposal.

**Comment by golfvert** [comment]
In the 1st comment, I was referring to:

```
5 | ship-sub-hourly | Ship based weather observations with a reporting frequency < 1 hour |  
6 | fixed-marine-platforms-hourly | Hourly weather observations from fixed marine platforms, e.g. rigs and offshore platforms |  
7 | fixed-marine-platforms-sub-hourly | Weather observations from fixed marine platforms, e.g. rigs and offshore platforms, with a reporting frequency < 1 hour |  
8 | fixed-land-stations-sub-hourly | Weather observations from fixed land stations with a reporting frequency < 1 hour |  
9 | mobile-land-stations-sub-hourly | Weather observations from mobile land stations with a reporting frequency < 1 hour
```

Based on the above, what is exactly the proposal ?

This ?
```
5 | ship | Ship based weather observations with a reporting frequency  |  
6 | fixed-marine-platforms | Weather observations from fixed marine platforms, e.g. rigs and offshore platforms |  
7 | fixed-land-station | Weather observations from fixed land stations  |  
8 | mobile-land-stations| Weather observations from mobile land stations |
```

The current list is:

synop,Surface observations,
temp,Upper air observations,
temp-ship,Radiosonde measurements from ships,
wind-profile,Wind profile measurements using PILOT balloons,
wind-profile-ship,Wind profile measurements using PILOT balloons from ships,
wind-profile-radar,Radar based wind profile measurements,
temperature-profile-radar,"Radar based temperature profile measurements, e.g. RASS"

What would be the full list ?

It looks like we could have SYNOP messages in 3 or 4 different topics depending on where it is coming from. Is that so ?

What is the purpose of making the difference, at the topic level, between:

```
fixed-marine-platforms
fixed-land-station
mobile-land-stations
```

**Comment by golfvert** [comment]
Just to repeat (again, sorry), if we have `fixed-` and `mobile-` it, necesarily, means that some users would be interested in having ONLY the fixed and not the mobile (or vice-versa) observations. Is that a use-case ?

**Comment by amilan17** [comment]
Based on what Enrico said, this would be the full list under surface-based-observations

```
synop,Surface observations,
ship,Ship based weather observations,
fixed-marine-platforms,"Weather observations from fixed marine platforms, e.g. rigs and offshore platforms",
temp,Upper air observations,
temp-ship,Radiosonde measurements from ships,
wind-profile,Wind profile measurements using PILOT balloons,
wind-profile-ship,Wind profile measurements using PILOT balloons from ships,
wind-profile-radar,Radar based wind profile measurements,
temperature-profile-radar,"Radar based temperature profile measurements, e.g. RASS",
```

**Comment by golfvert** [comment]
So, no more:

```
fixed-land-station
mobile-land-stations
```

**Comment by efucile** [comment]
Thank you @amilan17 I was trying to write the same thing.
The reason for having ship (which is very close to a synop from a ship) is because the data are identified and processed in a completely different way compared to synop and some of the ship data include marine observations. There is a requirement to keep them separate and they will have different WCMP2 records.
Regarding fixed-marine-platforms they need to be distinguished by the buoy data because they are completely different data and platforms.
fixed-land-station and mobile-land-station were introduced with sub-hourly to allow new types of data to be exchanged that can follow the synop format, but can have various other types of formats and are coming from land stations. These can be considered recommended for the moment and are not urgent. We can discuss about them in the next fast track and we are asking TT-WISMD to keep them on the work in progress.

**Comment by efucile** [comment]
@amilan17  can you please prepare a PR with this proposal for review of @tomkralidis and @golfvert ?

**Comment by golfvert** [comment]
> Regarding fixed-marine-platforms they need to be distinguished by the buoy data because they are completely different data and platforms.

I understand that we need to endorse the proposed changed in FT2024-2. So, I'll do it in https://github.com/wmo-im/wis2-topic-hierarchy/pull/193

However, when I read: 

> Regarding fixed-marine-platforms they need to be distinguished by the buoy data because they are completely different data and platforms.

I have the feeling that we are mixing two concepts here.
1. Creating a topic to enable user to get notification messages only for this topic
2. Creating a topic not to merge different kind of data at the _Notification Message_ level

I fully support 1. 
Not sure at all about 2.

I reiterate my offer to discuss in the context of the aforementioned cookbook. I'll create a separate issue for this.
