### ISSUE TITLE
update metadata publishing requirement

### ISSUE THREAD

**Issue by tomkralidis** [wmo-im/wis2-topic-hierarchy#179]
Using the example of `origin/a/wis2/ca-eccc-msc/metadata`, Requirement 1C states:

> Metadata SHALL be published to at least the level of the notification type (metadata).

This means that discovery metadata can be published to `origin/a/wis2/ca-eccc-msc/metadata`, `origin/a/wis2/ca-eccc-msc/metadata/core`, etc.  It was found that some Global Services were treating this requirement differently (some expecting a full Earth system discipline subtopic under `.../metadata`, for example).  Other Global Services were deleting everything witha subtopic below `.../metadata`.

To eliminate ambiguity, the below update is proposed:

> Metadata SHALL be published to the exact level of the notification type (metadata).

This means that discovery metadata can ONLY be published to `origin/a/wis2/ca-eccc-msc/metadata`

**Comment by amilan17** [comment]
Would this be a change that is introduced in FT2025-1?

**Comment by tomkralidis** [comment]
Yes, if that the earliest possibility.

**Comment by amilan17** [comment]
@tomkralidis this was not introduced in FT2024-2.
