### ISSUE TITLE
Level 9+ subcategories scope and management

### ISSUE THREAD

**Issue by amilan17** [wmo-im/wis2-topic-hierarchy#18]
As discussed, I think that maintenance (GitHub), publication (WMO Codes Registry) and validation (Broker) of the subcategories shall apply to **core data only**. Subcategories associated with recommended data are not in scope. 

If we are in agreement, then we should clearly document this. 
However, there are use cases where a particular domain might want to define subcategories for certain types of recommended data, e.g. NWP highly-recommended,  and we should consider options for supporting the normalization of these codes in a feasible manner.

**Comment by amilan17** [comment]
We should also reconsider this statement in the Readme: "

9 | earth-system-discipline-subcategory | As proposed by domain experts **_and further approved by INFCOM_**"

**Comment by tomkralidis** [comment]
TT-WISMD 2023-02-15:
- what level of governance/approval recommended need?  Is INFCOM approval too heavy?  Fast track?  Pull requests?
- chicken/egg problem (cannot block new centre-id from being locked out of topic hierarchy)
- how do we deal with lower level topic hierarchies not defined in core (beyond level 9)?  Are they discarded?

Numerous questions and clarifications on architecture of participation.

cc @efucile @golfvert

**Comment by golfvert** [comment]
> * what level of governance/approval recommended need?  Is INFCOM approval too heavy?  Fast track?  Pull requests?

I'd go for "Fast track". We need some form of formal approval. So Pull requests, probably not. But not to heavy so not INFCOM.
Considering the kind of things I approved on the fast track approach, seems OK to me.



> * how do we deal with lower level topic hierarchies not defined in core (beyond level 9)?  Are they discarded?

At the moment, the subscription on the French GB ends with #. Typically  `origin/a/wis2/swe/smhi/data/core/weather/surface-based-observations/#` So, everything below will go through. If we want to keep control on the topic hierarchy (and enforce the control of topics) then, the non compliant topics should be discarded at the GB level.

If we do that, the GBs will need to "import" the topics when approved and check that. What will be the policy for enforcing the discard? 
Say we have version 1.0. New version 1.1 is approved and then .2, .3,... what is the best way to allow some coexistence but not forever? Allowing 2 versions ? 3 versions ?



> * centre-id

I am confused with this... Is it centre or center? -id or _id? I don't recall having the final decision on that one.

**Comment by tomkralidis** [comment]
TT-WISMD 2023-05-10:
- recommendation data can be categorized accordingly
- +1 for reuse FT workflow (May/November)
