### ISSUE TITLE
bad gateway 502 

### ISSUE THREAD

**Issue by jowodo** [wmo-im/wis2-topic-hierarchy#183]
Hi, 

not sure if this is the right place to address this issue.
I am currently trying to check which topics are available. 
So I subscribed to all SYNOP topics over the weekend. 
I wanted to compare with the topics at
https://codes.wmo.int/wis/topic-hierarchy
, but the site does not seem to be available. 

Best,
Johann

**Comment by david-i-berry** [comment]
Closing, there were temporary issues with codes.wmo.int yesterday. These have now been resolved, cc @amilan17 .
