### ISSUE TITLE
Link to Identifiers in html DRAFT is stale

### ISSUE THREAD

**Issue by gespau** [wmo-im/wis2-topic-hierarchy#187]
I'm currently familiarizing myself with the WIS topic hierarchy (WTH) and noted that the link at https://wmo-im.github.io/wis2-topic-hierarchy/standard/wis2-topic-hierarchy-DRAFT.html#_codelists_bundle pointing to http://wis.wmo.int/spec/wth/1 is stale as http://wis.wmo.int/spec/ does not exist. 

Best regards, 
Johann

**Comment by tomkralidis** [comment]
@gespau this is expected.  We do plan to resolve specification/conformance URIs as part of future updates..
