### ISSUE TITLE
define dedicated GTS topic

### ISSUE THREAD

**Issue by tomkralidis** [wmo-im/wis2-topic-hierarchy#19]
As part of transition from GTS to WIS2, it is important to be able to clearly articulate what data is coming from GTS vs. WIS2.

**Comment by golfvert** [comment]
Option 1. Something "clever" using https://github.com/wmo-im/GTStoWIS2/blob/main/GTStoWIS2/TableCCCC.json
 and https://github.com/wmo-im/GTStoWIS2 . TTAAii will end up in something like `cache/a/wis2/mus/mauritius_plaisance/data/core/weather/surface-based-observations/upperair`
for TTAA `FIMP`

Option 2. Something "basic" TTAAii mapped directly onto a topic like cache/a/gts/TTAAii . Assuming here that GTS -> WIS2 gateway will be operated by Global Cache (JMA? DWD? ...)

Option 1 is more elegant (debatable...) but create yet another table to maintain and is prone to error.
Option 2 is plain and simple. When data is not sent by the source using WIS 2 solution, we keep it on a GTS like topic.
Some name and shame benefit as well. And if you want to receive TTAAii data subscription is obvious.

**Comment by josusky** [comment]
I suppose that during the transition we want to have GTS _islands_ amid the WIS 2.0 _sea_ and the _inhabitants_ of those _islands_ shall see no difference. For them, the whole _world_ should seem to be GTS. Therefore I think that the @golfvert 's option two is the only way. In option 1, part of the AHL (abbreviated heading line) is lost and is not recoverable. The conversion of AHL to the WIS 2.0 topic is still a valuable part of the transition. However, I think that GTS gateways shall advertise the data with topics like `cache/a/wis2/gts/TTAAii_CCCC_YYGGgg_BBB` (accidentally, in ISO 3166 no country has code "GTS" :-) ). But it can be also `origin/a/gts/TTAAii_CCCC_YYGGgg_BBB`, the point is, that this way another GTS gateway could seamlessly send the bulletin to a centre on a GTS _island_.
On second thought, the topic is not so important, it could even be just `origin/a/gts`, important is that the AHL (`TTAAii_CCCC_YYGGgg_BBB`) is in the `data_id` property of the notification (`gts/TTAAii_CCCC_YYGGgg_BBB` or `wis2/gts/TTAAii_CCCC_YYGGgg_BBB` or something like that).

PS: All this presumes that the GTS bulletins will be sent without AHL in the data (payload), which means that GTS gateway will transform the following GTS bulletin:
```
TEST01 TEST 050600 CCA
correction of a testing bulletin
```
into 
```
correction of a testing bulletin
```
sent with `data_id` containing `TEST01_TEST_050600_CCA` and (possibly) to a topic containing the same.
If that is not true, i.e. if the GTS gateways sent the whole bulletin as the payload their operation would be even simpler. That would make the topic (and `data_id`) unimportant, it could even be a constant value (`gts`).

**Comment by golfvert** [comment]
The use case here is "I have completed my transition from GTS to WIS2 I want to receive data from members still (and only on the GTS). So, it is ONLY GTS -> WIS2. As Kai points out WIS2 -> GTS in another can of worms.
If we consider that GTS data (GTS not yet available on WIS2) should be available for GTS users only, then having somehow to subscribe to TTAAii is not really a problem and is very simple (I think).

As a NMHS, I know which TTAAii I am/was receiving on the GTS, if I have a 1-to-1 mapping to a topic hierarchy, it is very easy...

If we do that we accept that non-GTS users (they have no clue on TTAAii) will not get GTS data (same definition as above) during the migration. It seems acceptable to me and it is yet another potential motivation for the migration.

**Comment by antje-s** [comment]
I agree that we are looking at bringing the GTS data into WIS2 during transition phase.
Since we want to be open in the WIS2 world and don't want to discourage new users, I would also prefer to have speaking topics (option 1). But a separation in the topic hierarchy is certainly useful (e.g. .../wis2/... versus .../gts/...). 

However, we must also consider that centers that have already been migrated no longer want to send data to the GTS. This means that the GTS data of these centers would no longer be available to centers that have not yet been migrated. So we should think about a return path to the GTS (only during transition phase with fixed ending date). As far as I know, there were file naming conventions for the old GTS data according to which TTAAii is included in the file name. If this is correct this should also make it possible to assign the old TTAAii products to speaking topics. In my opinion it may be acceptable that newer products (without TTAAii) then only would be available in WIS2. 
AHL in the data (payload) would be useful.

**Comment by josusky** [comment]
I think, that for GTS->WIS2 transition we do not need a special topic for the GTS data, on the contrary, we should try to seamlessly categorise all data into the one canonical `data_id`/`topic` hierarchy. The WIS2 early adopters shall be able to subscribe to e.g. `*/a/wis2/*/*/data/core/weather/surface-based-observations/upperair/#` without taking care about old GTS AHLs and file naming conventions.
I thought that the purpose of this task is to define a specific branch in the tree to advertise GTS data in a way that allows WIS2->GTS data forwarding to support not yet migrated centres. As notifications are quite "cheap" my understanding was that the role of the GTS gateways will be to publish notifications about GTS data to this secondary branch even if the same data is already published in the main branch by the originating centre.

@antje-s You are right that there is a file naming convention that allows assigning AHL to the file name. If I understand you right, you are proposing that the procedure for GTS gateways could be to use the main `data_id` branch (the "speaking topic") and just append a GTS-like file name at the end of it (which is more or less the current procedure in the WIS2 pilot). @tomkralidis would this be a "dedicated GTS topic" for you? The disadvantage that I see in such a solution is that it requires client-side filtering. As far as I know, MQTT does not allow partial wildcards i.e. subscription is not possible to `*/a/wis2/*/*/data/core/weather/surface-based-observations/upperair/A_USDL#`, am I right?

**Comment by josusky** [comment]
In other words, @tomkralidis @golfvert , could you clarify why we want to "clearly articulate what data is coming from GTS"? Is it to:
1. ease operation of GTS gateways?
2. ease the definition of subscriptions to people familiars with GTS?
3. other reasons?

BTW, point **2** would "cement" the use of AHLs in WIS2, which seems counterproductive.

**Comment by golfvert** [comment]
If we don't have the same understanding of the problem to solve, it is going to be hard :)

We shouldn't mix the two issues GTS -> WIS2 and WIS2 -> GTS.
Here it is about GTS -> WIS2 (aka - I have completed my transition from GTS to WIS2 I want to receive data from members still (and only on the GTS) ).

We have to open a different issue for WIS2 -> GTS

@tomkralidis if you agree on the point above, can we rename the issue as something clear about GTS -> WIS2 transition.

**Comment by golfvert** [comment]
@josusky the main objective for me is to make the GTS -> WIS2 operations as easy as possible for gateways operators and ex-GTS users (they have done the WIS2 and avoid having to maintain "special stuff" for that purpose.

So the Option 1. in my first comment we will need to maintain these mapping tables. And `mauritius_plaisance` may not be the final centre_id for this center. So, it creates (potentially) another difficulty.

I am making the assumption that users of "GTS->WIS2 gateway" are ex-GTS users and know what a TTAAii is. This is obviously debatable. But, in the grand scheme of things, it seems reasonable to me.

**Comment by josusky** [comment]
@antje-s no, no, if we have a separate branch in the topic hierarchy for GTS data, the notifications for the same data shall be published also in the normal (speaking) branch.

**Comment by kaiwirt** [comment]
@josusky You're speaking about two messages in two different topics for the same data?

**Comment by antje-s** [comment]
For publishing to normal (speaking) branch we also would need the mapping table CCCC to country/centre-id....
The values contained in TableA (mapping TTAAii to topic) could also be different to the WIS2 branch topics. Here, too, a regular comparison would be important. That's why, from my point of view, a separate branch has advantages. But the separate branch should be speaking, so that users can get along without instructions and also use these data.

**Comment by josusky** [comment]
@kaiwirt yes, the WIS2 nodes shall publish notifications (messages) under normal/pretty topics (and with pretty `data_id`) not cluttered with any TTAAii_CCCC_YYGGgg_BBB relics, while GTS gateway could use different ones. Otherwise, we would not need a specific topic for GTS data.
@antje-s yes, the mapping tables are still needed to help to transition the current GTS routing tables.

**Comment by golfvert** [comment]
I'm not sure I understand @josusky points above. 
In the context of GTS -> WIS2 gateway, the subject at hand here...
GTS data sent by site X under TTAAii will need to be injected onto WIS2 using an (yet to be) agreed topic. This will be the sole location of this data on WIS2.
Then again for GTS -> WIS2 we _**may**_ decide to put the TTAAii somewhere in the topic hierarchy. So, no mapping table required. Purely automatic...
For WIS2 -> GTS, it may be another story. But, let's not mix the two.

**Comment by josusky** [comment]
@golfvert there are mapping tables, that @antje-s created, which are used by some centres in WIS2 pilot to translate AHL (TTAAii...) into a nice topic, i.e. to insert data into the overall data hierarchy. The overall hierarchy is still under development, but that is a separate issue. Antje's mapping tables can be improved but in general, there is nothing special needed to be done for data coming from GTS. Whether you use Antje's tables or not, the GTS data are data as any other and have their place in the `data_id`/`topic` hierarchy. In WIS 2.0 we do not need to keep AHL in the topic.
The reason why I kept mentioning the opposite gateway (WIS2 -> GTS) was that I thought that you wanted to keep AHL somewhere in the topic (probably in a separate branch distributed in separate notifications) to make the work of such gateways easier. If it is out of scope, then we can close this issue, as there is nothing to be done here.

**Comment by antje-s** [comment]
Thanks, only one correction...the mapping tables are included in GTStoWIS2 and therefore work results of the whole TT-Protocols team ;-)

**Comment by tomkralidis** [comment]
TT-WISMD 2023-01-11
- use case / starting point?
- `cache.a.wis2` or `cache.a.gts` to delineate
- can use wildcards for subscription (`cache.a.*`)

Needs to be discussed further with @golfvert

**Comment by amilan17** [comment]
The ET-W2AT discussed this on 15 May see meeting minutes on Confluence and wmo-im/wis2-notification-message#24

**Comment by antje-s** [comment]
Should we close this issue as related to https://github.com/wmo-im/wis2pilot/issues/10
