### ISSUE TITLE
define business process for adding new centres/centre-id

### ISSUE THREAD

**Issue by amilan17** [wmo-im/wis2-topic-hierarchy#21]
use case: 
* WCMP2 validation of topic hierarchy will need to check the centre_id before it's approved by WMO

ideas: 
* add status column to topic hierarchy CSVs
* branch and PR workflows

**Comment by tomkralidis** [comment]
TT-WISMD 2023-02-15:
- discuss with @efucile @golfvert on formality of approval process/options/governance (pull request?  National PR approval?  Something else?)

**Comment by golfvert** [comment]
> * center_id

Anna, while the decision is still fresh, we go for centre-id, can you change your text? Just to avoid confusion on what is what !

**Comment by tomkralidis** [comment]
TT-WISMD 2023-04-12:
- once we get into FT workflow, we need to consider a fulsome list so that centres are not blocked from producing data
- can we add a `status` column to the centre-id (active, planned, etc.)
- need historical centre-id's for centres who stop providing data (for delayed mode/climate applications)
- FT workflow: delay in approval
- monitoring can help here to trigger centre-id publication for corrective action
  - gets added at next FT
- security implications?
  - centre-id needs to be approved by PR
  - being approved / registered is a pre-cursor to data publication
  - need trigger/notification to TT-WISMD to add centre-ids

**Comment by amilan17** [comment]
@kurt-hectic FYI, we will be adding centre-ids to the TH

**Comment by efucile** [comment]
**Decision**

This is part of the WIS2 node registration and the centre-id will be kept in the WIS2 registry.

**Comment by golfvert** [comment]
[20231013_Adding_NC_WIS2.pdf](https://github.com/wmo-im/wis2-topic-hierarchy/files/13355022/20231013_Adding_NC_WIS2.pdf)
[20231013_Adding_WIS2_Node.pdf](https://github.com/wmo-im/wis2-topic-hierarchy/files/13355023/20231013_Adding_WIS2_Node.pdf)

This will need some tweaking, but the overall process is agreed as described here.

**Comment by amilan17** [comment]
We still need to address how/when the centre-id is added to the topic-hierarchy. 

Centre-ids... 
1. are requested by the center
2. approved by WMO 
3. managed in the WIS2 Registry

I think these are the options available for implementation in the WTH
a. centre-id is added to the WTH in GitHub immediately and a new minor version of the WTH is released soon after
b. centre-id in TH is approved through fast-track approval ~2x/year
c. WIS2 Registry updates the WTH as needed/on a schedule, new minor version of WTH is released on a schedule

**Comment by golfvert** [comment]
I'd go for a. and I don't think the concept of minor version of the WTH exists and we don't need it either.
So "a. centre-id is added to the WTH in GitHub immediately" and done.

**Comment by tomkralidis** [comment]
>  So "a. centre-id is added to the WTH in GitHub immediately" and done.

This change then needs to propagate schemas.wmo.int as well as possibly elsewhere, for those doing WTH validation.  Which means even with `a`, we will need to apply minor version update somehow and communicate.

**Comment by tomkralidis** [comment]
Related: https://github.com/wmo-im/wis2-guide/issues/51

**Comment by golfvert** [comment]
"for those doing WTH validation". Not necessarily. The GB when subscribing to a new centre-id will be the mere fact of that subscription check that the centre-id is known and correct. So checking the TH by the GB, up to that level at least doesn't require any publication.
And, I am not sure that we will need strict TH validation elsewhere.

**Comment by tomkralidis** [comment]
TT-WISMD 2023-12-01:
- WTH stable branches are as per FT approval
- if there is an update to WTH that involves an addition of a centre-id, a new version of WTH tables/bundle are published immediately with the new centre-id to stable branch

**Comment by tomkralidis** [comment]
PR in #78
