### ISSUE TITLE
clarify role of country

### ISSUE THREAD

**Issue by tomkralidis** [wmo-im/wis2-topic-hierarchy#22]
Level 4 (country) is currently defined as:

> Lower case representation of ISO3166 3-letter code. Includes extensions for partner organizations

We need to clarify the role of the country in the documentation so that the topic hierarchy's county level is clearly defined to users.  Options:
- originator: party who created the resource
- distributor: party who distributes the resource
- other options?

**Comment by golfvert** [comment]
I guess this question is triggered by the discussion on CAP messages and the distribution role of Hong-Kong Observatory in the role called "swic". For me, here, HKO is providing a value added service. So, it is clearly not the originator. It is not only a distributor. It is adding "value". So, in this aspect, it seems logic to me the the "value added distributor" country (HKO as swic could be country xxa (see https://github.com/wmo-im/wis2-topic-hierarchy/issues/1#issuecomment-1384298237).

1. originator
2. or "value added distributor" 
as the country of origin.

**Comment by tomkralidis** [comment]
So this means originator or distributor (since the latter providing value add is implicit).  Any thoughts @josusky @antje-s ?

**Comment by antje-s** [comment]
originator and distributor is ok, maybe an explanation helps that it should be the first distributor of a product (original or extended) and not a re-distributor like a GC

**Comment by josusky** [comment]
I am not familiar with the HKO use case, but in general, adding value sounds pretty much like the generation of a new product :-)

**Comment by amilan17** [comment]
What is the use-case for including 'country' in the TH to begin with? To be able to search for data that was originally provided by a particular country? Is formal distribution or redistribution really "added value"?

**Comment by golfvert** [comment]
To @amilan17 mainly attribution and to recognise that WIS2 "membership" is managed by the various PRs of the countries. All WMO organisation is "country" oriented. We just acknowledged that it the Topic Hierarchy.

**Comment by antje-s** [comment]
It is helpful if country is the product originators (enhanced products could be considered as new products). This way, even after re-publish by GC, it is always possible to see where the notification started its journey. But then I wonder when country code "xxg" for Global Services will be used? Only for information on e.g. maintenance work etc.?

**Comment by antje-s** [comment]
"xxg" is now used, e.g. by swic (advisories-warnings) and GTStoWIS2 gateways.
Decision for country as the country to which product originators centre is officially assigned? And enhanced products considered as new products?

**Comment by 6a6d74** [comment]
Is this now superseded by decision on #58 ?

So DWD's GTS-to-WIS2 Gateway would now have id: `de-dwd-gts-to-wis2` or similar?

**Comment by tomkralidis** [comment]
> Is this now superseded by decision on #58 ?
> 

Yes (now live at https://wmo-im.github.io/wis2-topic-hierarchy/standard/wis2-topic-hierarchy-DRAFT.html#_centre_identification).

> So DWD's GTS-to-WIS2 Gateway would now have id: `de-dwd-gts-to-wis2` or similar?

Correct.
