### ISSUE TITLE
Version management of Topic Hierarchy

### ISSUE THREAD

**Issue by amilan17** [wmo-im/wis2-topic-hierarchy#25]
During the TT-NWPMetadata there were questions about how the versions of the topic hierarchy are managed. We should have it documented and also discuss with architecture team.

_updated: 31 May 2023_
### DECISION (draft)
- additions are expected (FT) as minor (x.y)
- updates/removals are breaking changes (not bound to FT) (x)
- domain independent, following pattern in TT-TDCF, for example
- how many versions to support?
- support n-1 (current/previous)
- Actual version notation will be addressed in https://github.com/wmo-im/wis2-topic-hierarchy/issues/11

**Comment by alexandreleroux** [comment]
Has using [semver.org](http://semver.org) been considered? Likely the most widely used versioning approach? Thanks!

**Comment by tomkralidis** [comment]
Given the version is used as part of the topic itself (level 2), the architecture team decided to go with a letter (i.e. `a`).

**Comment by amilan17** [comment]
Let me try to explain in more detail the conversation from TT-NWPMetadata workshop. 
Level 2 is the "Alphabetical version of the topic hierarchy". It is currently set to "a" and levels 1-8 are determined by WIS2. 

Levels 9+ will be decided by different communities. Does the version of level 2 change when new 9+ sub-categories are added or changed? Does it make sense to add a sub-versioning scheme for the sub-categories instead? 

This is related to Issue #18

**Comment by tomkralidis** [comment]
I guess this depends on the release lifecycle we want for the topic hierarchy.  i.e. do we want to follow a FT process similar to TT-TDCF (2x/year)?  Or do we want something more agile?

In either case, I suspect we will not start using real versioning until after the pilot phase.

**Comment by amilan17** [comment]
@tomkralidis I think we will manage the topic hierarchy values through fast-track procedures.

**Comment by amilan17** [comment]
I propose that we have a major and a minor version, e.g. "a.0" where "a" is for levels 1-7 and the numerical value is for levels 8+.

**Comment by sebvi** [comment]
I think my original question was the following (with context):

Levels 1-7 are managed by the WIS2 team directly and any change made to those levels will trigger a bump of the version (whatever the convention for this is: a, b, c or 1, 2, 3, or hash or whatever). 
My understanding is that each domain expert team is in charge of the levels 8+ and may want to version their work as well; i.e. when there is change in the hierarchy below level 8 (for instance introducing a new indirection in the hierarchy tree or reordering hierarchy levels, etc.).
As we don't currently have a way of versioning at our domain expert level, we have 2 options: 
- use the top level version and bump it, but that means each time a domain expert team requests a change, the version needs to bump for everyone and it means that version will be prone to change very frequently.
- introduce a minor version as the first level of hierarchy for each domain expert team. So below weather, ocean, climate, we immediately introduce a minor version, managed by each expert team, and only this one bumps when the team introduces a change in its domain specific sub-hierarchy. This change does not impact the other domain expert teams.

so my question was: would it be ok to introduce a minor version for each domain specific sub-hierarchy and make it mandatory for each domain expert team?

**Comment by 6a6d74** [comment]
Topic Hierarchy tracks the Data Category controlled vocab used in WCMP2.

The Data Category controlled vocabulary will be managed by Fast Track process -- just like all the other controlled vocabs.

The Topic Hierarchy _should_ follow.

Where WIS2 Nodes are publishing to un-official topics (e.g., not part of the topic hierarchy) this should get flagged so it can be fixed.

**Comment by amilan17** [comment]
> Topic Hierarchy tracks the Data Category controlled vocab used in WCMP2.

@6a6d74 for my understanding can you explain this statement? I don't think we have a "Data Category"....

**Comment by amilan17** [comment]
*   TH structure changes == new version
*   New topic (new leaf under the tree may make new data available) == same version
*   additions and minor revisions to content (without changing the meaning) to TH == same version

@efucile recommends the above for the version field without minor version

**Comment by tomkralidis** [comment]
TT-WISMD 2023-07-07:
- example TT-TDCF
  - any change warrants a version increment
  - do we envision support for multiple versions?  How do systems update/migrate
  - do clients subscribe to `cache/a/...`, or `cache/+/...`?
  - how many versions should brokers support? (2? So n-1)
  - options
   - should we add an extra level for WNM version?
  
@tomkralidis will discuss with W2AT/@golfvert for GB updates/upgrades.

**Comment by antje-s** [comment]
thought out loud...

If we don't want to introduce a separate TH-level for WNM version, we could possibly use a string under the current version level, which contains version information for TH and WNM, e.g. "th_a--wnm_a" (or later e.g. "th_d--wnm_a")
Pros:
- everyone who subscribes can be sure that they can handle the message content
Cons:
- no wildcard possible, otherwise both formats will be received at WNM change and can cause problems
- without wildcards also for every TH version change (which will be more frequent) subscription must be adjusted - impractical

On the other hand, the use of wildcards also bears a risk for TH, since no more messages would be received when renaming TH and a fixed TH subtree value is used for sub (e.g. cache/+/wis2/deu/dwd/data/core/weather/surface-based-observations/synop/#, renaming "surface-based-observations"). 
For this reason it might be better not to use wildcards for version, but then we should avoid too frequently updates. 
For extensions and non-critical updates, a web page with a list of all changes and notification via message could be sufficient and the version number is only increased for renames/deletions. If updates e.g. twice a year, several relevant adjustments can be made together (for all subdomains)

2 versions (n, n-1) supported by GB should be enough

**Comment by golfvert** [comment]
The proposal is to keep the "a" as much as we can for the version number. A change in a subdomain shouldn't imply an update to the version.  So, I'm not sure about the "DECISION" in #1

**Comment by 6a6d74** [comment]
We need a mechanism to inform the community when there are updates to the topic-hierarchies (level 9+) from experts. This should include updates to the controlled vocabularies. Can we use the same communication mechanism as is used for notifying members about updates to BUFR or GRIB codes?

**Comment by tomkralidis** [comment]
TT-WISMD 2028-08-28:
- no version bumps given subdomain changes (which will be frequent)
- could WTH have a WCMP2 record itself?
- could be communicated via a WIS2 operational newsletter
- given FT (notification of FT approval), published to operational newsletter and in manual on codes
- WTH will NOT be inline in manual on codes
- WIGOS updates example: links are in manual on codes

- what is a breaking change
  - removals
  - changes in structure
  - NOT additions
  - any rename
  - ONLY major changes to WNM
- subdomain updates should be considered case-by-case
- needs to be augmented with newsletter updates/similar communications

- brokers need to be aware of new centre ids
  - would be another workflow

**Comment by tomkralidis** [comment]
TT-WISMD 2023-09-25
- pending @gaubert action on managing version in WTH

**Comment by tomkralidis** [comment]
PR in #57.

**Comment by solson-nws** [comment]
I suggest we add guidance for the following:

1.  With each new version we need to define a deprecation date for previous version and when it will no longer be supported.
2.  Backward compatibility applicability with each new version
