### ISSUE TITLE
Determine publication approach in Codes Registry

### ISSUE THREAD

**Issue by amilan17** [wmo-im/wis2-topic-hierarchy#26]
We need to figure out how the Topic Hierarchy will be represented in the WMO Codes Registry, the format of the TH for other applications, e.g. the GB and GDC validation....

**Comment by amilan17** [comment]
see issue #34

**Comment by amilan17** [comment]
![image](https://github.com/wmo-im/wis2-topic-hierarchy/assets/5168866/9c790c86-32a6-4612-9fa1-47e056b3cdb8)

**Comment by amilan17** [comment]
![image](https://github.com/wmo-im/wis2-topic-hierarchy/assets/5168866/6690766c-1277-4314-a517-31b3ce1e033c)

**Comment by amilan17** [comment]
![image](https://github.com/wmo-im/wis2-topic-hierarchy/assets/5168866/27d2c489-0105-4118-9566-5e7641f8e450)

**Comment by amilan17** [comment]
@wmo-im/tt-wismd

**Comment by antje-s** [comment]
looks fine to me

**Comment by tomkralidis** [comment]
Looks good @amilan17.  Is there any documentation on tooling to be able to publish the topics automagically?

**Comment by amilan17** [comment]
Not yet, we can try to adopt the scripts used in WMDS repo: https://github.com/wmo-im/wmds/tree/master/scripts.

**Comment by amilan17** [comment]
@wmo-im/tt-wismd - Should we include the TH level in the description? A different option is to include it in the metadata of the code, which is not immediately visible. 

<img width="784" alt="image" src="https://github.com/wmo-im/wis2-topic-hierarchy/assets/5168866/9d25b5b5-d7ea-4611-b636-621c9a913a63">

![image](https://github.com/wmo-im/wis2-topic-hierarchy/assets/5168866/884de051-f73b-4de7-90fb-d2925e1453b5)

**Comment by antje-s** [comment]
+1 for adding to description

**Comment by tomkralidis** [comment]
Thanks to the work in https://github.com/wmo-im/wcmp2-codelists/issues/6 (thanks @antje-s / @josusky) , we now have a clearer picture of the workflow.

The scripts adapted in https://github.com/wmo-im/wcmp2-codelists/tree/main/scripts will be used as our starting point here in WTH.  They will need tweaking (sub-registers) given the hierarchical nature of WTH Earth System disciplines.

**Comment by amilan17** [comment]
/wis/topic-hierarchy

**Comment by amilan17** [comment]
@josusky @antje-s @tomkralidis -- Have you worked on scripts for publishing the WTH to the codes registry?

**Comment by josusky** [comment]
@amilan17 No, at least not me. I was not sure if we the scripts we have for WCMP2 code lists are "final" or we need to adjust them (e.g. add a new parameter/category) to have the codes correctly published.

**Comment by amilan17** [comment]
> I was not sure if we the scripts we have for WCMP2 code lists are "final" or we need to adjust them (e.g. add a new parameter/category) to have the codes correctly published.

@josusky To have the WIS registry displayed on the landing page, they need to be associated with the Category "WMO Volume I.2". However, we are looking at options to modify the category value to be more generic, because not all of the codes are associated with volume I.2.

**Comment by tomkralidis** [comment]
echo @josusky and that this will move forward once we have this fully working for WCMP2 codelists implementation (pending meeting next week).

We will be able to start with the WCMP2 codelist Python scripts, but will need to align them to variable level of topic levels (Registers/SubRegisters).

**Comment by tomkralidis** [comment]
+1 from myself as well -- great work @josusky / @antje-s !!

@amilan17 this is ready for you now for publication to codes.wmo.int.  Let us know if there are any questions or concerns.

**Comment by amilan17** [comment]
Topics are now published to https://codes.wmo.int/ with the status of Experimental. Note that centre-ids are not there at the moment, because they are going through a different approval process.
