### ISSUE TITLE
Add guidance/rules about including non-core/undefined topics in the TH tree

### ISSUE THREAD

**Issue by amilan17** [wmo-im/wis2-topic-hierarchy#30]
As I understand it so far, 

1.  All metadata records and notification messages for core and recommended data will include a topic hierarchy.
2.  Level 9+ sub-categories will be defined by the appropriate community for core data. 
3.  Values for core data will be proposed to and maintained by TT-WISMD. 
4.  All records for core data will use this defined TH.
5.  Records for recommended data will include as much as possible of the defined TH that applies.

The questions are:

1.  Can the TH include undefined topics at the end of the tree? e.g. "origin/../.../../data/recommended/weather/space-based-observations/**lightning**" or e.g. "origin/../.../../data/recommended/weather/**ship-based-observations**"
2. A sub-category may change from recommended to core. It would be useful to have this already defined for consistency. Where does the TT-WISMD draw the line between managing potentially all sub-categories and only core-subcategories? Is it important to make this clear? 
3. If we allow these undefined values, what happens to them in GB and GC? 

These questions arose during the NWPMetadata workshop in January.

**Comment by golfvert** [comment]
Some elements of answer. Just my opinion...

> Can the TH include undefined topics at the end of the tree? 
No. The level 9 (subcategories) and potentially below MUST be defined by the relevant experts from each domain. Something that is not agreed (and then, typically fast-tracked...) can't be used.

> A sub-category may change from recommended to core.
The categories should be the same for core and recommended. The "tree" below these two options are the same. Typically, the current level 8 (categories) is the same for both.

> A sub-category may change from recommended to core.
For me we shouldn't. Therefore, GB should discard unapproved sub-categories. The GC will never see them.

**Comment by amilan17** [comment]
@golfvert Thank you for your thoughts. 
I think there might be scenarios where the datatype in the recommended category do not have a Level 9+ sub-category to use. Should this be a concern?

**Comment by tomkralidis** [comment]
TT-WISMD 2023-03-08
- allowing arbitrary subtopics under the official WMO TH:
  - should be allowed (principle of extensibility)
  - subscriptions can be used for wildcarding (`+`, `#`)
  - still, may be heavy on users and broker
  - one resource/data granule, representation agnostic
  - what does GB need to validate?
    - core levels?
    - core + domain levels?
    - the bundle (programmatically) will provide what topics are in scope

**Comment by kaiwirt** [comment]
> * allowing arbitrary subtopics under the official WMO TH
> * should be allowed (principle of extensibility)

How do we ensure, that two different centers do not use the same arbitrary topic for different things?

Consider

- (Center-)Local extensions?
- Register new topics at some registry (codes.wmo.int?)?

**Comment by josusky** [comment]
@kaiwirt If two centres use the same sub-topic "extension" somewhere below the levels that are officially recognized, it will not cause any problem, because the centre ID is high in the hierarchy, thus the whole topic will still be unique. e.g:
`wis2/ita/meteoam/data/core/weather/surface-based-observations/synop/my_cool_sub-category`
vs
`wis2/deu/dwd/data/core/weather/surface-based-observations/synop/my_cool_sub-category`

**Comment by amilan17** [comment]
@kaiwirt @josusky the risk (or benefit?!) of allowing uncontrolled is extensions is when there is a wildcard in the TH query. However, I think we need to accept this risk in favor of keeping the management of THs reasonable. 

`wis2/+/+/data/core/weather/surface-based-observations/synop/my_cool_sub-category`

**Comment by amilan17** [comment]
> How do we ensure, that two different centers do not use the same arbitrary topic for different things?
> 
> Consider
> 
> *   (Center-)Local extensions?
> *   Register new topics at some registry (codes.wmo.int?)?

@kaiwirt the idea is that only the officially approved topics will be published to the WMO codes registry. The group or data provider who wants to use "uncontrolled" values need to consider proposing new topics to this TT or managing them seperately (if they are managed at all). I'm not in favor of prefixing the local extensions with "(Center)-" or anything else.

**Comment by golfvert** [comment]
Before wondering if there is a risk of clash between two centres each deciding to publish messages under ..../my_cool_sub-category (without the same definition of what is cool), I still don't see what would be the benefit for our community to allow those free level(s) of topic hierarchy.
I guess there must be. I don't get them, though. I can't see a user able to know that topic a exists for centre A, b for B and so on and applying subscription filters on those... The main (sole?) purpose of the topic hierarchy is to get a logic categorisation of data, enabling filtering at the MQTT level.

Can we first discuss the use cases?

**Comment by josusky** [comment]
The point is that a certain number of levels (nine?) in the hierarchy will be standardized central by WMO, and several more sub-level will be added by domain specialists (dedicated expert teams). It is not clear how far this needs to go and how rigid it needs to be. So the use case for allowing "free" sub-topics, in somewhere like 12th level, is flexibility and lowering of the barrier for entry to WIS.

**Comment by golfvert** [comment]
IMHO, the main benefit of agreeing on the topic hierarchy is to allow users to subscribe (and therefore filter) on topics they are (potentially) interested in. If a topic is created locally without any consistency between WIS2 Nodes, then having those "my_super_cool-topic" is missing the filtering goal. 

So, as you point out, we have defined the first 9 levels as "global" for all WMO programs and then each domain experts will have to define the sublevels (the story doesn't tell how many).
With this, I would hope that 99% of the data/datasets/API will find the place where they belong.
For data (to make it shorter) that would not fit in one of the agreed place of the topic tree, then we may want to add an agreed default option where "unclassified" data would go. This would be a temporary (for me) solution while the domain experts agree on an extra topic in their branch.

At the moment, we haven't defined this "default" place. That might be missing...

**Comment by 6a6d74** [comment]
Discussion transferred from email thread about topic hierarchy for SWIC (HKO) republishing warnings...

@armstrong >

> To support the pilot of sending CAP messages aggregated in SWIC2 to WIS2, I have prepared the list of topic for existing Member countries/territories of which their CAPs are aggregated in SWIC2.  I should be grateful to have your comments.


@golfvert >

> Thank you for this proposal.
> I will just use one country as an example.
> You propose: origin/a/wis2/xxa/swic/data/core/weather/warning-AFG
> That part: origin/a/wis2/xxa/swic/data/core/weather  is OK for me and is consistent with the current agreed topic hierarchy.
> However, according to [https://github.com/wmo-im/wis2-topic-hierarchy/tree/main/topic-hierarchy](https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fwmo-im%2Fwis2-topic-hierarchy%2Ftree%2Fmain%2Ftopic-hierarchy&data=05%7C01%7Cjeremy.tandy%40metoffice.gov.uk%7Cc20ced2be43c4343d85808db2b7ca8fe%7C17f1816120d7474687fd50fe3e3b6619%7C0%7C0%7C638151587000192300%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C7000%7C%7C%7C&sdata=I374o%2BvXUZV6xwsm%2FLAfwKdpzXGFDTqC8s0nMZGq3xA%3D&reserved=0) the next level for warnings in the "weather" category (look at the weather.csv file) should be advisories-warnings.
> So it would be origin/a/wis2/xxa/swic/data/core/weather/advisories-warnings 
> 
> And then the next question is whether we want to add a sub topic including country names so that MQTT subscription might be limited to a particular country or group of countries.
> We have started a similar discussion (without clear conclusion just yet) on whether the lower topic levels could be freely chosen by members to cover a particular situation.
> SWIC case falls exactly in that situation, I think.
> Look at (and contribute is you want) to this github discussion [https://github.com/wmo-im/wis2-topic-hierarchy/issues/30](https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fwmo-im%2Fwis2-topic-hierarchy%2Fissues%2F30&data=05%7C01%7Cjeremy.tandy%40metoffice.gov.uk%7Cc20ced2be43c4343d85808db2b7ca8fe%7C17f1816120d7474687fd50fe3e3b6619%7C0%7C0%7C638151587000192300%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C7000%7C%7C%7C&sdata=ZoNHQQCa9BXHEje9PVBV0YaCUkWOrHwcBwNysm511Q0%3D&reserved=0)
> Therefore, we have, I think, two options:
> 
> 1. All warnings in the origin/a/wis2/xxa/swic/data/core/weather/advisories-warnings  topic level
> 2. Add a sublevel using the country name to allow such a filter, for example, origin/a/wis2/xxa/swic/data/core/weather/advisories-warnings/afg
> afg must be in lower case. We decided that topic hierarchy will be lower case only.
> Then if not "afg" directly it could be country_afg or we could have yet another level with the continent so origin/a/wis2/xxa/swic/data/core/weather/advisories-warnings/asia/afg 
> So, filtering on a continent base would be easy. The is however a bit awkward as there is no approved 3-letter code for continent... 
> 
> As we are in a pilot phase where the purpose is to experiment what has been agreed and testing solutions when not yet approved, I would propose to start with origin/a/wis2/xxa/swic/data/core/weather/advisories-warnings/afg 
> and see how it goes and if it works for us.
> 
> This is just my opinion though :)

And my comment ... 

Armstrong – I think you’ve made a great start with your proposal. And I agree with Rémy’s amendments too. 

Someone could subscribe to the 

`origin/a/wis2/xxa/swic/data/core/weather/advisories-warnings`

topic and use client-side filtering if they wanted (e.g. looking at the spatial extent).

But being able to subscribe at the country level also seems useful, e.g.:

`origin/a/wis2/xxa/swic/data/core/weather/advisories-warnings/gbr`

Let’s try things out in the pilot and see what users prefer.

**Comment by amilan17** [comment]
I had a hallway conversation with @golfvert and @6a6d74 a couple weeks ago and we decided that _for now_ the topic hierarchy shall NOT be extensible for any extra categories that are not defined in the GitHub, because at this time it will establish a baseline approach and simplifies the complexity. This can be revisited after the pilot project is over.

**Comment by amilan17** [comment]
> Discussion transferred from email thread about topic hierarchy for SWIC (HKO) republishing warnings.

@6a6d74 can you open a new issue for this topic? It's tangential to this one and I'd like to keep track of it separately. Thanks!

**Comment by amilan17** [comment]
Decision for team to approve: 

For now, all values in the topic hierarchy need to be approved and available. It is not extensible with ad-hoc values as needed. This can be revisited later after the pilot phase if needed.

**Comment by tomkralidis** [comment]
TT-WISMD: 2023-05-10
- +1 for a fixed hierarchy
- a WIS2 Node can always publish to a higher level topic
  - is this an issue?  Are data producers able to do this?  How can/will brokers deal with "dangling" data at higher level topics?
  - should we provide documentation on this?
  - do not allow higher than centre id?  Can only publish data AFTER level 9
- consider issues of migration (from experimental to release)

ACTION: add text to require data to be published greater than level 9.

To be continued / implemented once https://github.com/wmo-im/wis2-topic-hierarchy/issues/38#issuecomment-1542209396 is implemented.

**Comment by tomkralidis** [comment]
TT-WISMD 2023-09-12:
- discussed in #35

**Comment by tomkralidis** [comment]
TT-WISMD 2023-09-25
- closing in lieu of #35
