### ISSUE TITLE
update definition of country

### ISSUE THREAD

**Issue by amilan17** [wmo-im/wis2-topic-hierarchy#33]
It needs to be clear that the 'country' is for the location of the data center, not the geographic location of the dataset.

**Comment by yhe-wmo** [comment]
Noting that some WMO Members are not countries, is it better to name this level "member" or something else other than "country"?

**Comment by tomkralidis** [comment]
> It needs to be clear that the 'country' is for the location of the data center, not the geographic location of the dataset.

@amilan17 yes, we can articulate the "data centre" or "issuing centre" as part of the documentation (related #46)

> Noting that some WMO Members are not countries, is it better to name this level "member" or something else other than "country"?

@yhe-wmo at the country level, we support WMO RAs (i.e. RAI: `xxa`, RAII: `xxb`, etc.) as well as global centres (`xxg`), using the "xx*" notation in alignment with ISO 3166 alpha3.  Thus any member (at the centre-id level), would be able to associate with a country, WMO RA, or global entity.

**Comment by amilan17** [comment]
> Noting that some WMO Members are not countries, is it better to name this level "member" or something else other than "country"?

@yhe-wmo pointed out to me that Hong Kong is a Member but should not be referred to as a country.

**Comment by 6a6d74** [comment]
superseded by #58
