### ISSUE TITLE
provide publication artifacts

### ISSUE THREAD

**Issue by tomkralidis** [wmo-im/wis2-topic-hierarchy#34]
Currently, we have a GitHub Actions CI that uses [pywcmp's bundle workflow](https://github.com/wmo-im/wis2-topic-hierarchy/blob/main/.github/workflows/bundle.yml#L21) to publish a first pass/working level JSON file of all topics.

There are a few issues with this workflow:

- centres should be bound to countries only (per https://github.com/wmo-im/wis2-topic-hierarchy/pull/29#issuecomment-1460056820)
- the list will explode as domain topics begin to populate
- this workflow should be part of this repository, not pywcmp.  Note that there will be some relation to #26 (which in contrast would provide different inputs to codes.wmo.int)

Assigning to @antje-s and @josusky; additional help is welcome (cc @wmo-im/tt-wismd)

**Comment by antje-s** [comment]
When going through csv files exactly, I noticed that so far the mapping between the centres and the respective country is missing. 
country.csv includes always centre-id as child value and centre-id.csv does not contain a column with an assignment to a country...

**Comment by yhonda21** [comment]
In addition, I wonder how this center ID is linked to the name of RSMCs?

**Comment by antje-s** [comment]
...maybe we can call a py-script from the action, which does the merge. A first suggestion for such a merge script I put to a new branch:
https://github.com/wmo-im/wis2-topic-hierarchy/blob/JSON_bundle/merge2json/mergeTopic.py  
But so far it contains only a fixed number of levels and can certainly be improved by an experienced programmer.

**Comment by amilan17** [comment]
> When going through csv files exactly, I noticed that so far the mapping between the centres and the respective country is missing. country.csv includes always centre-id as child value and centre-id.csv does not contain a column with an assignment to a country...

see #39

**Comment by hhaddouch** [comment]
**ET-W2AT Washington 13-15 November 2023** 
the publication mechanism is agreed, and need to be implemented
