### ISSUE TITLE
Document basic business rules for the Topic Hierarchy

### ISSUE THREAD

**Issue by amilan17** [wmo-im/wis2-topic-hierarchy#35]
Through the development of sub-discipline categories many questions are arising and I think that the domain specific communities would benefit from more guidance on TH rules for the Level 9+ values.  

https://github.com/wmo-im/wis2-topic-hierarchy/wiki/Change-Management.
https://github.com/wmo-im/wis2-topic-hierarchy/wiki/Business-rules 

## Scope
wmo-im/wis2-topic-hierarchy#18

## Extensibility
wmo-im/wis2-topic-hierarchy#30 

## Versioning
wmo-im/wis2-topic-hierarchy#25  

Other Related issues:  
wmo-im/wis2-guide#38
wmo-im/wis2-topic-hierarchy#21

**Comment by amilan17** [comment]
see specification.

**Comment by tomkralidis** [comment]
TT-WISMD 2023-09-12:
Encoding of values at all levels:
- SHALL be lowercase
- SHALL be IA-5 (ASCII)
- dashes, not dots
- SHALL be unique
  - registration to support determining/validating

ACTION: add as requirement

**Comment by amilan17** [comment]
the levels shall not be re-ordered

**Comment by tomkralidis** [comment]
PR in #57.
