### ISSUE TITLE
Organize level 8+ sub-topics 

### ISSUE THREAD

**Issue by amilan17** [wmo-im/wis2-topic-hierarchy#38]
Levels 1 - 7 are organized as flat CSVs, but at some point the sub-topics will need to branch off. For discussion, below are some screenshots of the current organization and some alternative options.

**Comment by amilan17** [comment]
Level 1-8

![](https://github.com/wmo-im/wis2-topic-hierarchy/assets/5168866/efdbd1d5-f48f-4917-894f-beeaca15f126)

**Comment by amilan17** [comment]
Levels 8+ as described by the Unified Data Policy with domain expert input so far highlighted in yellow. 

![](https://github.com/wmo-im/wis2-topic-hierarchy/assets/5168866/b5717ad2-0dd2-4c4d-bc4e-5ffe7ba1aaad)

**Comment by amilan17** [comment]
Option A, following current approach above, should require that we maintain consistency whereever possible.

![](https://github.com/wmo-im/wis2-topic-hierarchy/assets/5168866/0922e94a-1106-491a-9c06-2c1a4b11106c)

**Comment by amilan17** [comment]
Option B, branching occurs at level 9 as "datatype or category" for predictions, observations, advisories-warnings. 

![](https://github.com/wmo-im/wis2-topic-hierarchy/assets/5168866/85a1f86f-1443-4af3-9732-a6c552e5df5c)

**Comment by tomkralidis** [comment]
TT-WISMD 2023-05-10:

- go with option A (consistent sub-category under each Earth System Discipline [level 9])
- add common subtype under earth system discipline:
  - surface-based-observations
  - space-based-observations
  - advisories-and-warnings
  - predictions (whether to subqualify or not?)

...but allow domains to request additional common subtype as needed.

- need to verify validation of topics complexity from GB (@golfvert)

**Comment by amilan17** [comment]
@alexandreleroux recommends having the top level be "observations" and the type under that (space, ground, surface)

**Comment by golfvert** [comment]
Up to level 8 and some 9 (when available in Res. 1), we want to stick to Res. 1 denomination. I don't think this proposal is consistant with this.

**Comment by amilan17** [comment]
see draft at: https://github.com/amilan17/wis2-topic-hierarchy/tree/main/topic-hierarchy

**Comment by amilan17** [comment]
> Up to level 8 and some 9 (when available in Res. 1), we want to stick to Res. 1 denomination. I don't think this proposal is consistant with this.

In my opinion, UDP is too inconsistent to follow exactly. For example, "space-based" and "surface-based" are only sub-categories under **weather** and **space-weather** disciplines, but satellite data are also listed for **hydrology** and **cryosphere** disciplines, but not under any sub-category. Furthermore, I find it hard to believe that core satellite data may not apply at all under **atmosphere, ocean or climate**.... 

For reference, see Annex 1 of WMO Unified Data Policy: [https://library.wmo.int/index.php?lvl=notice_display&id=22100](https://library.wmo.int/index.php?lvl=notice_display&id=22100)

**Comment by tomkralidis** [comment]
TT-WISMD 2023-06-22:
-  @amilan17 / @antje (and possible @jsieland / @gaubert) will prepare something for the next meeting (2023-07-07)

**Comment by antje-s** [comment]
...wondering if it is really not consistant to add a level "observations" with WMO Unified Data Policy (https://library.wmo.int/doc_num.php?explnum_id=11256 , Annex 1)

1. Weather-related data
1.1 Core observational data
1.1.1 Surface-based
1.1.2 Space-based

e.g.
origin/a/wis2/deu/dwd/data/core/weather/surface-based-observations/
update to
origin/a/wis2/deu/dwd/data/core/weather/observations/surface-based/

**Comment by yhe-wmo** [comment]
> update to
> origin/a/wis2/deu/dwd/data/core/weather/observations/surface-based/

This is indeed a recommendation put forth by TT-NWPMD as well, in order to maintain a simple and concise structure on Level 9.

**Comment by golfvert** [comment]
> > update to
> > origin/a/wis2/deu/dwd/data/core/weather/observations/surface-based/

We could. 

Looking at hydrology in the mind map above:

<img width="214" alt="Screenshot 2023-06-23 at 18 58 25" src="https://github.com/wmo-im/wis2-topic-hierarchy/assets/6681762/cedae42d-cf21-4f91-bdfa-c938998a6891">

If we create an observation level, what do we do with the other two categories ?

The real (only ?) goal of the topic hierarchy is to have a filtering mechanism to receive only useful messages. With MQTT we have two wildcards ? (anything at this level) and # (anything below this level). With this in mind, from a user point of view and management of subscription point of view, what is the "best" option.

````
origin/a/wis2/deu/dwd/data/core/weather/surface-based-observations/
or
origin/a/wis2/deu/dwd/data/core/weather/observations/surface-based/
````

Looking again at the 4 categories for hydrology, what is useful to filter for a user ? The 4 at the same level ? 2 at one level and two below observation ?
For me, these are the key questions...

**Comment by antje-s** [comment]
Suitable filter options for the different use cases is relevant, I absolutely agree with that. But from my point of view, there is nothing to be said against it for this reason as well....

new TH:
.../weather/observations/surface-based/
.../weather/observations/space-based/
.../weather/analysis-prediction/
.../weather/advisories-warnings/

old TH:
.../weather/surface-based-observations/
.../weather/space-based-observations/
.../weather/analysis-prediction/
.../weather/advisories-warnings/

But maybe I'm overlooking some use cases, the ones I would think of are:
1) all observations
subscribe to 
new - .../weather/observations/#
old - .../weather/surface-based-observations/#    &    .../weather/space-based-observations/# (to avoid simultaneous subscription to  .../weather/analysis-prediction/ and .../weather/advisories-warnings/)
+1 for new

2) only surface-based-observations
new - .../weather/observations/surface-based/#
old - .../weather/surface-based-observations/#
even though the new one has one more level, the total string length is hardly longer, so i would rate both versions as equal

3) only space-based-observations
see 2

4) for analysis-prediction & advisories-warnings 
no difference

5) all messages under weather
new - .../weather/#
old - .../weather/#
no difference

**Comment by amilan17** [comment]
**Tag up 2023-07-05 (w/ Antje, Julia and Anna)**
* (Antje) notifications about services should be classified as 'report' and 'service' is not needed, because it's only information for the users
* prefer to have /observations  (9) (with the space-based, surface-based, etc (9)) as options underneath, because users can filter out level 10 -- if they don't care if it's space-based or surface -based

**Comment by tomkralidis** [comment]
TT-WISMD 2023-07-07:
- @amilan17 to create PR based on the approach (will not include climate)

**Comment by amilan17** [comment]
PR #53 includes decisions discussed in July tag up: [https://github.com/wmo-im/wis2-topic-hierarchy/issues/38#issuecomment-1621604073](https://github.com/wmo-im/wis2-topic-hierarchy/issues/38#issuecomment-1621604073)

1.  Is it ok to have flat levels (1-7) and then nested levels (8+)? It feels like we are changing the rules mid-game.... 
2.  Should every level have a CSV listing the child folders? This is necessary for committing "empty" folders in GH but is it useful for other things too? (see [https://github.com/wmo-im/wis2-topic-hierarchy/tree/38-organize-level-8%2B-sub-topics/topic-hierarchy/weather](https://github.com/wmo-im/wis2-topic-hierarchy/tree/38-organize-level-8%2B-sub-topics/topic-hierarchy/weather) vs https://github.com/wmo-im/wis2-topic-hierarchy/tree/38-organize-level-8%2B-sub-topics/topic-hierarchy/atmospheric-composition)
3.  Child column is removed from nested levels, do we still need it?
4.  Do we need definitions?

**Comment by tomkralidis** [comment]
TT-WISMD 2023-09-12:
- PR #53 to be reviewed and approved/merged thereafter (@amilan17 to update)

**Comment by golfvert** [comment]
Are we saying that any combination of elements from each level is a valid topic ?
So `.../data/core/climate/observations/forecast/green-house-gases ` is acceptable (I chose on purpose the weirdest combination).

**Comment by amilan17** [comment]
comments from meeting with Enrico: 
- we need the tree approach

**Comment by SimonElliottEUM** [comment]
We need a tree approach to cover the diversity of data destined for WIS 2.0. As @golfvert and @efucile mention, we leave the door open for nonsense on one hand (.../data/core/space-weather/observations/surface-based/...), and preclude precision on the other

**Comment by tomkralidis** [comment]
Associated PR now in #70
