### ISSUE TITLE
add parent column for country to centre-id

### ISSUE THREAD

**Issue by tomkralidis** [wmo-im/wis2-topic-hierarchy#39]
There is a constraint between countries and centre-id's where one country may have 0..n associated centre-id's.

~We need to represent this relationship to prevent possibilities such as:~
~`origin/a/wis2/usa/eccc-msc/...`~

We need to represent this relationship to be able to map centre-ids to countries.

One option can be adding a `parent` column to `centre-id.csv` would help express this constraint between these two levels.

1. are there other options we should consider?
2. are there similar situations between other parent/child levels?

**Comment by josusky** [comment]
1. The `country.csv` contains column "Child" which is useless as the relation is not 1..1 but 1..n. Technically we could merge the `centre-id.csv` with `country.csv`, but for clarity, I suggest keeping both. I do not see more options. Thus, reduce `country.csv` to `Name` (code) and `Description` (actual name), and add `Country` (parent) column to `centre-id.csv.
2. Sure, if you remember Anna's charts many levels have sub-levels, so we can express it by having some sort of "Parent" column in (almost) every CVS file. On the other hand, we should remove the "Child" columns as all the relations (if they exist) are 1..n (where `n` might be `1` in some cases but not as a general rule).

**Comment by david-i-berry** [comment]
To use the example above, what if the USA decides on the acronym `eccc-msc` for a centre? `origin/a/wis2/usa/eccc-msc/...` then becomes valid and is not something we want to prevent.

**Comment by tomkralidis** [comment]
Yes.  So the question becomes articulating the parent (country) accordingly.

**Comment by golfvert** [comment]
As we are going to merge country/centre-id into one field, this issue becomes irrelevant.

**Comment by 6a6d74** [comment]
see related issue #58

**Comment by tomkralidis** [comment]
We will close once #34 is addressed.

**Comment by tomkralidis** [comment]
Deemed invalid given the level 8+ structure put forth in #63.
