### ISSUE TITLE
add centre-id for ECMWF

### ISSUE THREAD

**Issue by amilan17** [wmo-im/wis2-topic-hierarchy#43]
According to issue #1 , ECMWF will be associated with RAVI, but we need to have the centre id in the topic hierarchy also.

**Comment by sebvi** [comment]
are we going to use the "old" CCCC ICAO codes for the centre-id for continuity from old GTS TTAAiiCCCC filename stuff?

Alternatively, there is the Common Code Table C-11 used by GRIB2 and BUFR4 for  [centres
](https://github.com/wmo-im/CCT/blob/master/C11.csv)  but that table does not standardised names with hyphens
 
I don't have a strong opinion on this.

**Comment by tomkralidis** [comment]
@sebvi we are not bound to the "old" codes.  PR in #45.  The general approach is:

- lower case
- `-`, not `_`

Note: this will be further articulated as part of the development of the technical regulations for WTH.

**Comment by sebvi** [comment]
As I said I don't have a strong opinion regarding this so happy with using "ecmwf" and hyphens for expanded acronyms.
