### ISSUE TITLE
add mock country and centre-id

### ISSUE THREAD

**Issue by tomkralidis** [wmo-im/wis2-topic-hierarchy#48]
For testing purposes it would be valuable to have a mock country and centre-id.

Initial proposal of:

- country = zzz
- centre-id = testing

cc @golfvert @kaiwirt @hhaddouch

**Comment by golfvert** [comment]
As zzz is user assigned as xxa-xxg is. Fine by me.
For centre-id, I'd go for wis2node_1, wis2node_2,...

**Comment by antje-s** [comment]
+1 for country = zzz
for centre-id I would prefer the suggestion of @golfvert, as we would then be more flexible and could fire from different testnodes from different countries at the same time

**Comment by tomkralidis** [comment]
TT-WISMD 2023-09-12:
- need to validate use case
- Guide would need to document for GBs to ignore messages from zzz
- If we assume zzz, can we still use the existing (real) countries?

**Comment by golfvert** [comment]
Use case: test performance, reliability, time to cache with a "controlled" source.
During the hackathon week those will be required, I think.
Then, if GB ignore zzz then they are useless... GB are the entry gates.
And zzz is a fake country like xxa-xxg.
So, I don't see a link between "zzz" and existing (real) countries...

**Comment by tomkralidis** [comment]
TT-WISMD 2023-12-01:
- is this still a requirement, or can centres use the (new) `experimental` topic for testing?
- having mock centre-ids may result in test data being downloaded by clients expecting operational data
- if we need `test` centre-ids for performance/etc. testing, we *could* require that the test centre-id always published to an `experimental` subtopic for purposes of testing?

**Comment by josusky** [comment]
I think we should close this issue. The topic sub-tree under "experiment" is a better solution.
