### ISSUE TITLE
Establish initial list of centre-id values

### ISSUE THREAD

**Issue by tomkralidis** [wmo-im/wis2-topic-hierarchy#5]
We need an initial list of centre-id's to be able to properly classify and identify data.

cc @efucile @golfvert

**Comment by efucile** [comment]
The center-id should identify the WIS2 node originator of the data. I think we should define a registration process for the WIS2 nodes and one step will be the choice of center-id. I think we should start with the centers contributing to the pilot phase. I am not for defining a list of phantom center-ids.

**Comment by golfvert** [comment]
+1 with Enrico. Something to discuss in an upcoming W2AT meeting, I guees!

**Comment by tomkralidis** [comment]
This was brought up earlier today during [wis2box discussions](https://github.com/wmo-im/wis2box/issues/228#issuecomment-1311732438) on validating topic hierarchy.

This should be covered in the context of the WIS2 registry WP (process, guidance on defining, etc.).

**Comment by golfvert** [comment]
Before making it worldwide (and potentially difficult to manage) let's make it tailored for the pilot phase. We have 20ish names to agree.
I'll take meteo-france 😄 and fra. No surprise here!!
What is important here is lowercase only and no diacritics symbols. So no Météo-France!!

**Comment by golfvert** [comment]
Shall we, for the time being, just have a shared excel file somewhere with country and centre_id?

**Comment by efucile** [comment]
better to have a csv file on github, at least version control is ensured

**Comment by amilan17** [comment]
related to issue #21
