### ISSUE TITLE
add guidance on centre-id

### ISSUE THREAD

**Issue by tomkralidis** [wmo-im/wis2-topic-hierarchy#51]
WTH should provide guidance (requirements or recommendations) on how centres should craft their centre-id value.  Examples:

- dashes, not underscores
- no special characters
- no infrastructure (i.e. ! `my-centre-wis2node`)
- additional guidance?

cc @golfvert

**Comment by golfvert** [comment]
The wis2node should be based on the name of the institution, whether it is an acronym (eg. smhi, cma,...) or a "full name" (eg. meteo-france, maroc-meteo,...).

**Comment by tomkralidis** [comment]
TT-WISMD 2023-09-12:

ACTION:
- add "should be based on the name of the institution" as recommendation

**Comment by amilan17** [comment]
from @solson-nws: Consider adding language for centre-id that makes it clear the distinction between organization vs. originator/provider level. Perhaps one of the examples could be something like noaa-nws-spc

**Comment by golfvert** [comment]
I don't understand the point above.
For me, for NWS the "base" of potential multiple centre-id should be: us-noaa-nws

Depending on local choices, one organization may decide to run multiple WIS2 Nodes (eg. one for the NC function, one every DCPC function,...).
In this case, we would have the "base" eg. fr-meteofrance and then specialized WIS2 Nodes:
- fr-meteofrance-vaac
- fr-meteofrance-nwp

And following the same logic, the Global Broker operated by Météo-France could be:
- fr-meteofrance-globalbroker

At the moment, the Global Broker is not producing messages for itself. However, this might change to eg. use MQTT messages for monitoring/management purposes.

So, WIS2 Node, Global Caches, Global Brokers, Global Discovery Catalogs,... everything would have it own centre-id.

**Comment by 6a6d74** [comment]
Agree with @golfvert ... the centre-id should provide some form of descriptive token, ideally based on the WMO function that the centre is fulfilling. For many, that will simply be `nc`.

For example: `uk-metoffice-nc`

**Comment by efucile** [comment]
**Decision**
The Secretariat will make sure that the rules for centre-id are applied when a centre is submitting a WIS2 node registration

The rules are in the specs [centre identification](https://wmo-im.github.io/wis2-topic-hierarchy/standard/wis2-topic-hierarchy-DRAFT.html#_centre_identification )

Examples and the specs will be provided in the guide.
