### ISSUE TITLE
Having version in the top levels of the topic hierarchy is potentially a problem as it can be really disruptive for all users

### ISSUE THREAD

**Issue by gaubert** [wmo-im/wis2-topic-hierarchy#60]
Having the version in the top of the tree is a problem because a change anywhere in the topic hierarchy and requiring an increase of the version number will force all topic publishers to update their configuration. 

See below an example where it is decided to rename Ocean into "Marine" a one of the sub domains. In that case the version would be incremented from a to b and all messages publishers would then be required to update their destination topic configuration at the same time because the topic paths would not be valid anymore. 

This means that potentially an centre publishing only messages in the hydrology domain would have to update its topic paths because the Ocean sub tree has been modified. A lot of messages consumers could also be impacted. 

Here is an example with the original tree:

<img width="951" alt="original-tree" src="https://github.com/wmo-im/wis2-topic-hierarchy/assets/1482/f433b56f-06fa-483e-a56f-f77e8d1c53db">

Here would be the modified tree with Marine:

<img width="1042" alt="Screenshot 2023-10-06 at 08 56 57" src="https://github.com/wmo-im/wis2-topic-hierarchy/assets/1482/01cbb0e5-364a-4ce3-abb9-08f62c707997">

Because the version is incremented and at the top of the tree, all publishers in order to publish messages in their correct new topics will have to update their configuration (their topic paths have changed). 

This is like an unnecessary big bang approach when only the publisher (and consumers) impacted by the change should make a modification of their systems.

My proposal would be to remove the version number from the topic hiearchy. The changes and version number should be managed outside of the tree implementation and announced/communicated on the main WIS2 web presence (Global Catalogue, the web site around the Global Broker if there is one). Then a parallel phase where both old and new trees will be supported by the Broker for a given period and then the dead branch removed at the end of the parallel message distribution.

Cases to manage are:
- modify/add a node: In that case it can be inserted in the existing tree.
- deletion of a node and reattaching or not all the subtopic nodes.

Below is an example where core would be removed from the tree and all its sub-topics reattached to data.

Here is the original tree with the new structure (sub-topics attached to data) maintained in parallel.

<img width="1362" alt="Screenshot 2023-10-06 at 09 18 53" src="https://github.com/wmo-im/wis2-topic-hierarchy/assets/1482/ccd68b12-7f3d-418f-adb2-92b7b73090e5">

Then the core topic is deleted at the end of the parallel period:

<img width="1002" alt="Screenshot 2023-10-06 at 09 05 04" src="https://github.com/wmo-im/wis2-topic-hierarchy/assets/1482/20e24432-1c7d-4a2c-b5b7-42674715372f">

In that case all the publishers not impacted by the tree branch change can continue publishing without changing there configuration. 

Did I forget something ? Thoughts ?
@tomkralidis @jsieland @amilan17 @josusky @antje-s @solson-nws ....

In general it seems to me that we are going to have a lot of surprises with the topic hierarchy when implemented and we should not make it yet part of any "standards" or official WMO paper from which it will be very difficult to change it afterward.

This should be done once the Pilot or frist implementation phase has been completed.

**Comment by tomkralidis** [comment]
W2AT 2023-11-15

Given the requirements on versioning in [WTH](https://wmo-im.github.io/wis2-topic-hierarchy/standard/wis2-topic-hierarchy-DRAFT.html#_versioning), along with data management principles on additions/deletions, numerous version increments (a->b->c) are not envisioned at this time.
