### ISSUE TITLE
Update included value in version.csv 

### ISSUE THREAD

**Issue by antje-s** [wmo-im/wis2-topic-hierarchy#8]
...hope it is ok to ask directly here.
Should the value for version not be adjusted to "v04" instead of "a"?
see https://github.com/wmo-im/wis2-topic-hierarchy/blob/main/topic-hierarchy/version.csv

**Comment by amilan17** [comment]
related to #25 #11

**Comment by kaiwirt** [comment]
Can this be closed?

**Comment by tomkralidis** [comment]
Closing in lieu of #25
