### ISSUE TITLE
add topics for aviation data (for ICAO)

### ISSUE THREAD

**Issue by amilan17** [wmo-im/wis2-topic-hierarchy#85]
* weather
   * aviation
      * metar
      * taf
      * qvaci

**Comment by amilan17** [comment]
@6a6d74

**Comment by amilan17** [comment]
@tomkralidis @wmo-im/tt-wismd

**Comment by 6a6d74** [comment]
- origin/a/wis2/{centre-id}/data/recommended/weather/aviation/metar
- origin/a/wis2/{centre-id}/data/recommended/weather/aviation/taf
- origin/a/wis2/{centre-id}/data/recommended/weather/aviation/qvaci

**Comment by efucile** [comment]
1.	Aerodrome Observation (METAR)
2.	Aerodrome Forecast (TAF)
3.	Quantitative Volcanic Ash Concentration Information (QVACI)

**Comment by tomkralidis** [comment]
PR in #92
