### ISSUE TITLE
country ISO3166 3-letter code current in capital letters

### ISSUE THREAD

**Issue by antje-s** [wmo-im/wis2-topic-hierarchy#9]
Currently the country code is in upper case
https://github.com/wmo-im/wis2-topic-hierarchy/blob/main/topic-hierarchy/country.csv
Should we change to lower case for the topic values to have everything in lower case or not?

**Comment by tomkralidis** [comment]
Given we are based on ISO 3166 alpha3, I would think we would stay with upper case for consistency.

**Comment by tomkralidis** [comment]
See the ISO OBP for ISO 3166: https://www.iso.org/obp/ui

Options:
1. Country codes SHALL be UPPERCASE
2. Define as 'WMO' country codes that are based on 3166 alpha3, but lowercased (includes possible additions from #1)
3. Other options?

cc @golfvert @efucile @maaikelimper

**Comment by golfvert** [comment]
I don't have access to full iso standards ($$)...
Can you copy/paste the iso 3166 statement about this?
The example is in upper case. But, is it mandatory?

**Comment by golfvert** [comment]
Typically, the two-letter version of the country ode is used in lower case for domain name (DNS). 
If not explicitly requested to be always in UPPERCASE in ISO 3166, I would go for all lowercase in the topic hierarchy. Hence, lower case for country code too.

**Comment by tomkralidis** [comment]
I can't see anything normative (publicly at least).  Lower case would be a better fit given the rest of our core topic hierarchy is lower-cased.  The question is whether we want/are able to say that our country codes are ISO 3166 alpha-3 valid.

Having said this, we can see from the 3166 Annex F outline:
- Principles for short form lower case
- Principles for short form capitals

A PR in #12 implements lowercase if there is no objection.

+1 from me for lowercase with clarification in the documentation.

**Comment by golfvert** [comment]
The "beauty" (grrr...) of iso standards is that they are not public. 
I agree, from what I can see and practical usage (eg DNS) lowercase doesn't seem to contradict the standard.
So, I would go to lowercase in the entire topic hierarchy.

**Comment by tomkralidis** [comment]
Implemented as lowercase in #12
