### ISSUE TITLE
Normalization of WTH references to artifacts such as schemas, codes...

### ISSUE THREAD

**Issue by amilan17** [wmo-im/wis2-topic-hierarchy#90]
Ensure consistency of WTH URLs and resources outside of the Manual on WIS. Below are lists of what exists today in WTH.

- Document location
  - https://community.wmo.int/wis2-topic-hierarchy
- The normative provisions in this Standard are denoted by the URI:
  - http://wis.wmo.int/spec/wth/1
- The WIS2 Topic Hierarchy Notification codelist bundle can be found at
  - https://schemas.wmo.int/wth/1.0/wth.zip
- A browseable codelist can be found at 
  - https://codes.wmo.int/wth
- Requirements Class
  - http://www.wmo.int/spec/wth/1/req/core
- A zip file of all the approved topics is available at 
  - https://schemas.wmo.int/wth/a/1.0/wth.zip.
- A browseable and searchable codelist of all topics can be found at 
  - https://codes.wmo.int/wth.
- Conformance with this standard shall be checked using the tests specified in the Conformance Class Abstract Test Suite (Normative). It is published at 
  - https://schemas.wmo.int/wth/a/1.0/ats.

**Comment by amilan17** [comment]
@tomkralidis

**Comment by amilan17** [comment]
Community page: 
https://community.wmo.int/en/activity-areas/wis/wis2-topic-hierarchy

**Comment by amilan17** [comment]
As discussed with Tom, the plan is to publish to schemas.wmo.int like this: 

**Schemas site:**
- https://schemas.wmo.int/wth/a/1.0
  -    standard
       -  PDF (from GH tag release)
  -    examples (maybe)
  -    shemas
  -    wth.zip (GH tag release, includes everything including examples)

http://www.wmo.int/spec/wcmp/2/conf/core --> this will change to wis.wmo.int/...

Update all xml snippets and update URLs from GH to codes.wmo.int

**Comment by tomkralidis** [comment]
- PR in #96 
- Release process updated in https://github.com/wmo-im/wis2-topic-hierarchy/wiki/ReleaseProcess
